# Prometheus Alerting Rules for x0tta6bl4
# These rules monitor connection health, latency, and system stability

groups:
  - name: x0tta6bl4-connection-alerts
    interval: 30s
    rules:
      # High latency alert
      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(x0tta6bl4_request_duration_seconds_bucket[5m])) > 0.5
        for: 2m
        labels:
          severity: warning
          service: x0tta6bl4
        annotations:
          summary: "High latency detected on {{ $labels.instance }}"
          description: "95th percentile latency is {{ $value }}s (threshold: 0.5s)"
          runbook_url: "https://wiki.internal/x0tta6bl4/runbooks/high-latency"

      # Connection drops alert
      - alert: ConnectionDrops
        expr: rate(x0tta6bl4_connection_errors_total[5m]) > 0.1
        for: 1m
        labels:
          severity: critical
          service: x0tta6bl4
        annotations:
          summary: "Connection drops detected on {{ $labels.instance }}"
          description: "Connection error rate is {{ $value }} errors/sec"
          runbook_url: "https://wiki.internal/x0tta6bl4/runbooks/connection-drops"

      # Circuit breaker open alert
      - alert: CircuitBreakerOpen
        expr: x0tta6bl4_circuit_breaker_state == 2
        for: 0s
        labels:
          severity: warning
          service: x0tta6bl4
        annotations:
          summary: "Circuit breaker is open for {{ $labels.circuit_name }}"
          description: "Circuit breaker {{ $labels.circuit_name }} has opened due to failures"
          runbook_url: "https://wiki.internal/x0tta6bl4/runbooks/circuit-breaker"

      # High retry rate alert
      - alert: HighRetryRate
        expr: rate(x0tta6bl4_retry_attempts_total[5m]) > 0.5
        for: 2m
        labels:
          severity: warning
          service: x0tta6bl4
        annotations:
          summary: "High retry rate on {{ $labels.instance }}"
          description: "Retry rate is {{ $value }} retries/sec"
          runbook_url: "https://wiki.internal/x0tta6bl4/runbooks/high-retry-rate"

  - name: x0tta6bl4-system-alerts
    interval: 30s
    rules:
      # Service down alert
      - alert: ServiceDown
        expr: up{job="x0tta6bl4"} == 0
        for: 1m
        labels:
          severity: critical
          service: x0tta6bl4
        annotations:
          summary: "x0tta6bl4 service is down on {{ $labels.instance }}"
          description: "Service has been down for more than 1 minute"
          runbook_url: "https://wiki.internal/x0tta6bl4/runbooks/service-down"

      # High memory usage alert
      - alert: HighMemoryUsage
        expr: (process_resident_memory_bytes{job="x0tta6bl4"} / 1024 / 1024) > 1024
        for: 5m
        labels:
          severity: warning
          service: x0tta6bl4
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is {{ $value }} MB"
          runbook_url: "https://wiki.internal/x0tta6bl4/runbooks/high-memory"

      # High CPU usage alert
      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total{job="x0tta6bl4"}[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: x0tta6bl4
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is {{ $value }}%"
          runbook_url: "https://wiki.internal/x0tta6bl4/runbooks/high-cpu"

  - name: x0tta6bl4-security-alerts
    interval: 30s
    rules:
      # Security event alert
      - alert: SecurityEvent
        expr: increase(x0tta6bl4_security_events_total[5m]) > 0
        for: 0s
        labels:
          severity: info
          service: x0tta6bl4
        annotations:
          summary: "Security event detected on {{ $labels.instance }}"
          description: "Event type: {{ $labels.event_type }}"
          runbook_url: "https://wiki.internal/x0tta6bl4/runbooks/security-events"

      # Failed authentication alert
      - alert: FailedAuthentication
        expr: rate(x0tta6bl4_auth_failures_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
          service: x0tta6bl4
        annotations:
          summary: "High authentication failure rate on {{ $labels.instance }}"
          description: "Auth failure rate is {{ $value }} failures/sec"
          runbook_url: "https://wiki.internal/x0tta6bl4/runbooks/auth-failures"

  - name: x0tta6bl4-mesh-alerts
    interval: 30s
    rules:
      # Mesh node disconnected
      - alert: MeshNodeDisconnected
        expr: x0tta6bl4_mesh_node_connected == 0
        for: 2m
        labels:
          severity: warning
          service: x0tta6bl4
        annotations:
          summary: "Mesh node {{ $labels.node_id }} is disconnected"
          description: "Node has been disconnected for more than 2 minutes"
          runbook_url: "https://wiki.internal/x0tta6bl4/runbooks/mesh-node-down"

      # Low mesh connectivity
      - alert: LowMeshConnectivity
        expr: x0tta6bl4_mesh_connected_peers < 2
        for: 5m
        labels:
          severity: warning
          service: x0tta6bl4
        annotations:
          summary: "Low mesh connectivity on {{ $labels.instance }}"
          description: "Only {{ $value }} peers connected (minimum: 2)"
          runbook_url: "https://wiki.internal/x0tta6bl4/runbooks/low-mesh-connectivity"

      # High mesh latency
      - alert: HighMeshLatency
        expr: histogram_quantile(0.95, rate(x0tta6bl4_mesh_latency_seconds_bucket[5m])) > 0.2
        for: 3m
        labels:
          severity: warning
          service: x0tta6bl4
        annotations:
          summary: "High mesh latency on {{ $labels.instance }}"
          description: "95th percentile mesh latency is {{ $value }}s"
          runbook_url: "https://wiki.internal/x0tta6bl4/runbooks/high-mesh-latency"
