// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadQos returns the embedded CollectionSpec for qos.
func loadQos() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_QosBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load qos: %w", err)
	}

	return spec, err
}

// loadQosObjects loads qos and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*qosObjects
//	*qosPrograms
//	*qosMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadQosObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadQos()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// qosSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type qosSpecs struct {
	qosProgramSpecs
	qosMapSpecs
	qosVariableSpecs
}

// qosProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type qosProgramSpecs struct {
	XdpQosEnforcer *ebpf.ProgramSpec `ebpf:"xdp_qos_enforcer"`
}

// qosMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type qosMapSpecs struct {
	SlicePolicyMap *ebpf.MapSpec `ebpf:"slice_policy_map"`
}

// qosVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type qosVariableSpecs struct {
}

// qosObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadQosObjects or ebpf.CollectionSpec.LoadAndAssign.
type qosObjects struct {
	qosPrograms
	qosMaps
	qosVariables
}

func (o *qosObjects) Close() error {
	return _QosClose(
		&o.qosPrograms,
		&o.qosMaps,
	)
}

// qosMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadQosObjects or ebpf.CollectionSpec.LoadAndAssign.
type qosMaps struct {
	SlicePolicyMap *ebpf.Map `ebpf:"slice_policy_map"`
}

func (m *qosMaps) Close() error {
	return _QosClose(
		m.SlicePolicyMap,
	)
}

// qosVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadQosObjects or ebpf.CollectionSpec.LoadAndAssign.
type qosVariables struct {
}

// qosPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadQosObjects or ebpf.CollectionSpec.LoadAndAssign.
type qosPrograms struct {
	XdpQosEnforcer *ebpf.Program `ebpf:"xdp_qos_enforcer"`
}

func (p *qosPrograms) Close() error {
	return _QosClose(
		p.XdpQosEnforcer,
	)
}

func _QosClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed qos_x86_bpfel.o
var _QosBytes []byte
