#!/bin/bash
# x0tta6bl4 Mesh Agent Installer
# Usage: curl -sL maas.x0tta6bl4.io/install | bash -s -- --token <KEY>
set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'

INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/etc/x0t"
DATA_DIR="/var/lib/x0t"
SERVICE_NAME="x0t-agent"
RELEASES_URL="https://github.com/x0tta6bl4/agent/releases/latest/download"

log() { echo -e "${GREEN}[x0t]${NC} $1"; }
err() { echo -e "${RED}[x0t] ERROR:${NC} $1" >&2; exit 1; }

# Parse args
TOKEN=""
API_URL="https://maas.x0tta6bl4.io"
while [[ $# -gt 0 ]]; do
    case $1 in
        --token) TOKEN="$2"; shift 2;;
        --api-url) API_URL="$2"; shift 2;;
        --help) echo "Usage: $0 --token <TOKEN> [--api-url <URL>]"; exit 0;;
        *) shift;;
    esac
done

[ -z "$TOKEN" ] && err "Join token required. Use: --token <TOKEN>"

# Detect architecture
ARCH=$(uname -m)
case "$ARCH" in
    x86_64)  BINARY="x0t-agent-linux-amd64";;
    aarch64) BINARY="x0t-agent-linux-arm64";;
    armv7l)  BINARY="x0t-agent-linux-armv7";;
    *)       err "Unsupported architecture: $ARCH";;
esac

log "x0tta6bl4 Mesh Agent Installer"
log "Architecture: $ARCH → $BINARY"

# Check root
[ "$EUID" -ne 0 ] && err "Run as root: sudo bash -s -- --token $TOKEN"

# Download binary
log "Downloading $BINARY..."
curl -fsSL "$RELEASES_URL/$BINARY" -o "$INSTALL_DIR/x0t-agent" || err "Download failed"
chmod +x "$INSTALL_DIR/x0t-agent"
log "Installed to $INSTALL_DIR/x0t-agent"

# Create dirs
mkdir -p "$CONFIG_DIR" "$DATA_DIR"

# Generate config
NODE_ID="x0t-$(head -c 4 /dev/urandom | xxd -p)"
cat > "$CONFIG_DIR/agent.yaml" <<EOF
# x0tta6bl4 Mesh Agent Configuration
# Auto-generated by install.sh

node_id: "$NODE_ID"
api_endpoint: "$API_URL"
join_token: "$TOKEN"
listen_port: 5000
pqc_enabled: true
obfuscation: none
log_level: info
data_dir: "$DATA_DIR"
heartbeat_interval_sec: 30
EOF

log "Config written to $CONFIG_DIR/agent.yaml"

# Install systemd service
cat > /etc/systemd/system/$SERVICE_NAME.service <<'UNIT'
[Unit]
Description=x0tta6bl4 Mesh Agent (Data Plane)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/x0t-agent --config /etc/x0t/agent.yaml
Restart=always
RestartSec=5
LimitNOFILE=65535
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/var/lib/x0t /etc/x0t
PrivateTmp=true
MemoryMax=128M
StandardOutput=journal
StandardError=journal
SyslogIdentifier=x0t-agent

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable $SERVICE_NAME
systemctl start $SERVICE_NAME

log ""
log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
log "  ${CYAN}x0tta6bl4 Agent Installed!${NC}"
log "  Node ID: $NODE_ID"
log "  Status:  systemctl status $SERVICE_NAME"
log "  Logs:    journalctl -u $SERVICE_NAME -f"
log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
