"""Non-bounty income map for autonomous x0tta6bl4 agents."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any


SCHEMA = "x0tta6bl4.non_bounty_income_map.v1"
CLAIM_BOUNDARY = (
    "This map ranks non-bounty earning routes. It proves only local analysis and "
    "artifact planning. It does not prove platform account access, accepted work, "
    "customer demand, payout eligibility, received funds, or tax/payment compliance."
)


@dataclass(frozen=True)
class IncomeOpportunity:
    opportunity_id: str
    title: str
    channel: str
    revenue_model: str
    first_artifact: str
    next_machine_step: str
    why_agent_fits: str
    zero_budget_note: str
    gates: tuple[str, ...]
    risks: tuple[str, ...]
    repo_assets: tuple[str, ...]
    source_urls: tuple[str, ...]
    cash_speed: int
    zero_budget_fit: int
    automation_fit: int
    payout_clarity: int
    token_efficiency: int
    market_validation: int


OPPORTUNITIES: tuple[IncomeOpportunity, ...] = (
    IncomeOpportunity(
        opportunity_id="agentpact_offer_pack",
        title="AgentPact service offer",
        channel="agent marketplace",
        revenue_model="USDC escrow-backed agent-to-agent deals on Base.",
        first_artifact=".tmp/non-bounty/agentpact_offer.json",
        next_machine_step="Generate an agent offer for data extraction, repo triage, and structured reports.",
        why_agent_fits="AgentPact exposes MCP/API flows for register, offer, matches, deals, and delivery.",
        zero_budget_note="Free tier claims no wallet required to start; payout still needs settlement setup later.",
        gates=("external_account_or_api_key", "deal_acceptance", "wallet_or_payout_setup"),
        risks=("new_marketplace", "unverified_real_payout_to_this_wallet", "needs_reputation"),
        repo_assets=("src/sales/paid_task_selector.py", "scripts/ops/run_paid_task_watch_loop.py"),
        source_urls=("https://agentpact.xyz/",),
        cash_speed=7,
        zero_budget_fit=9,
        automation_fit=9,
        payout_clarity=7,
        token_efficiency=8,
        market_validation=6,
    ),
    IncomeOpportunity(
        opportunity_id="sporeagent_task_runner",
        title="SporeAgent task runner",
        channel="agent task marketplace",
        revenue_model="Small paid tasks with proof-of-work verification.",
        first_artifact=".tmp/non-bounty/sporeagent_worker_profile.json",
        next_machine_step="Create a worker profile and poll tasks for web scraping, tests, translation, and reports.",
        why_agent_fits="The site advertises MCP-native tasks, agent bidding, accepted delivery, and verification.",
        zero_budget_note="No infrastructure cost for task search; account and payout setup are still external gates.",
        gates=("platform_account", "accepted_bid", "deliverable_approval", "payout_setup"),
        risks=("limited_current_task_depth", "unknown_payout_history_for_our_agent", "competition"),
        repo_assets=("scripts/ops/run_paid_task_hunter.py", "src/sales/paid_task_selector.py"),
        source_urls=("https://sporeagent.com/",),
        cash_speed=8,
        zero_budget_fit=8,
        automation_fit=8,
        payout_clarity=6,
        token_efficiency=7,
        market_validation=6,
    ),
    IncomeOpportunity(
        opportunity_id="apify_actor_factory",
        title="Apify Actor factory",
        channel="automation marketplace",
        revenue_model="Pay-per-event Actor monetization plus affiliate commission from Actor pages.",
        first_artifact=".tmp/non-bounty/apify_actor_backlog.json",
        next_machine_step="Package one useful scraper/checker as an Apify Actor with JSON input and output.",
        why_agent_fits="Actors are Docker-packaged tools with JSON input/output; x0tta6bl4 already has scanners and reports.",
        zero_budget_note="Can build locally first; publishing and payout need an Apify account and payout method.",
        gates=("apify_account", "actor_publication", "usage_or_referrals", "payout_method"),
        risks=("needs_distribution", "not_instant_cash", "platform_payout_may_need_paypal_or_bank"),
        repo_assets=("scripts/ops/run_paid_task_watch_loop.py", "src/sales/product_ideas.py"),
        source_urls=(
            "https://apify.com/partners/open-source-fair-share",
            "https://apify.com/partners/affiliate",
        ),
        cash_speed=4,
        zero_budget_fit=8,
        automation_fit=9,
        payout_clarity=9,
        token_efficiency=8,
        market_validation=9,
    ),
    IncomeOpportunity(
        opportunity_id="x402_paid_micro_api",
        title="x402 paid micro API",
        channel="pay-per-request API",
        revenue_model="Agents or programs pay per HTTP request for data, reports, or MCP tools.",
        first_artifact=".tmp/non-bounty/x402_service_catalog.json",
        next_machine_step="Define one paid endpoint: repo-risk-score, bounty-filter, or scraper-result API.",
        why_agent_fits="x402 lets HTTP resources request payment and lets agents pay automatically.",
        zero_budget_note="Local prototype is free; live route needs deployment, wallet, and customers.",
        gates=("deployment", "wallet", "payment_facilitator", "customer_discovery"),
        risks=("no_existing_traffic", "payment_flow_can_move_real_money", "needs_abuse_limits"),
        repo_assets=("src/sales/paid_task_selector.py", "src/api/maas/endpoints/marketplace.py"),
        source_urls=(
            "https://developers.cloudflare.com/agents/tools/payments/x402/",
            "https://www.coinbase.com/developer-platform/products/x402",
        ),
        cash_speed=7,
        zero_budget_fit=8,
        automation_fit=9,
        payout_clarity=9,
        token_efficiency=9,
        market_validation=8,
    ),
    IncomeOpportunity(
        opportunity_id="gate402_x402_catalog",
        title="Gate402 x402 catalog import",
        channel="x402 service registry",
        revenue_model="Import the existing x402 manifest; buyers discover the service and pay USDC per call.",
        first_artifact=".tmp/non-bounty/gate402_import_status.json",
        next_machine_step="Keep the public x402 API online and poll Gate402 search until the active service is indexed.",
        why_agent_fits="x0tta6bl4 already exposes a public x402 manifest with eight small paid JSON tools.",
        zero_budget_note="No gas, deposit, KYC, or private user wallet is needed for message-signing registration.",
        gates=("public_https_endpoint", "manifest_validation", "search_indexing", "buyer_call"),
        risks=("new_marketplace", "search_indexing_delay", "unverified_first_sale_to_this_wallet"),
        repo_assets=("src/sales/x402_paid_api.py", "scripts/ops/gate402_import_service.py"),
        source_urls=(
            "https://gate402.net/for-agents.md",
            "https://gate402.net/openapi.json",
        ),
        cash_speed=7,
        zero_budget_fit=9,
        automation_fit=9,
        payout_clarity=9,
        token_efficiency=9,
        market_validation=7,
    ),
    IncomeOpportunity(
        opportunity_id="agent402_api_listing",
        title="Agent402 API listing",
        channel="agent API marketplace",
        revenue_model="Register an existing x402 endpoint; buyers discover it by intent and pay per request.",
        first_artifact=".tmp/non-bounty/agent402_listing.json",
        next_machine_step="Point Agent402 at the current x402 paid API discovery URL and list repo triage plus API docs.",
        why_agent_fits="x0tta6bl4 already has HTTPS, x402 402 responses, discovery JSON, and MCP manifest.",
        zero_budget_note="The paid endpoint is already local/ngrok; account or sign-in gate may still block registration.",
        gates=("seller_registration", "service_review_or_indexing", "buyer_call", "onchain_payment"),
        risks=("new_marketplace", "registration_gate", "unverified_first_sale_to_this_wallet"),
        repo_assets=("src/sales/x402_paid_api.py", "scripts/ops/run_x402_paid_api.py"),
        source_urls=("https://marketplace.agent402.app/",),
        cash_speed=6,
        zero_budget_fit=7,
        automation_fit=9,
        payout_clarity=8,
        token_efficiency=9,
        market_validation=7,
    ),
    IncomeOpportunity(
        opportunity_id="agora402_native_registry",
        title="Agora402 native x402 registry",
        channel="x402 agent registry",
        revenue_model="Register a native x402 endpoint; buyers discover the agent by category and pay per call.",
        first_artifact=".tmp/non-bounty/agoragentic_seller_watch_status.json",
        next_machine_step="Keep the verified public listing online and poll invocations, earned balance, webhooks, and wallet balance.",
        why_agent_fits="Agora402 is built for machine-readable discovery and direct per-call x402 payment to agent endpoints.",
        zero_budget_note="Existing public endpoint can be reused; no proposal spend is needed, but a buyer call is still required.",
        gates=("public_https_endpoint", "registry_visibility", "buyer_call", "x402_payment"),
        risks=("buyer_demand_unknown", "new_marketplace", "unverified_first_sale_to_this_wallet"),
        repo_assets=("src/sales/x402_paid_api.py", "scripts/ops/agoragentic_seller_watcher.py"),
        source_urls=("https://agora402.io/",),
        cash_speed=6,
        zero_budget_fit=9,
        automation_fit=9,
        payout_clarity=8,
        token_efficiency=9,
        market_validation=6,
    ),
    IncomeOpportunity(
        opportunity_id="the402_provider_listing",
        title="the402 provider listing",
        channel="x402 service marketplace",
        revenue_model="List a data/API/automated service and receive USDC through x402 or escrowed marketplace flow.",
        first_artifact=".tmp/non-bounty/the402_provider_listing_plan.json",
        next_machine_step="Prepare a provider listing for the current domain-health, URL snapshot, and API-docs endpoints.",
        why_agent_fits="the402 supports data APIs, automated services, human services, digital products, subscriptions, and MCP discovery.",
        zero_budget_note="Can reuse the current public x402 API; provider onboarding and catalog acceptance are external gates.",
        gates=("provider_account", "service_listing", "catalog_visibility", "buyer_call_or_order"),
        risks=("external_account_gate", "catalog_currently_sparse", "unverified_first_sale_to_this_wallet"),
        repo_assets=("src/sales/x402_paid_api.py", "docs/commercial/agentmart_products/domain_health_lite_workflow.md"),
        source_urls=("https://the402.ai/",),
        cash_speed=5,
        zero_budget_fit=8,
        automation_fit=9,
        payout_clarity=8,
        token_efficiency=8,
        market_validation=5,
    ),
    IncomeOpportunity(
        opportunity_id="four_o_two_rest_api_publish",
        title="402.rest API publisher",
        channel="x402 API marketplace",
        revenue_model="Publish a paid x402-ready API endpoint and earn per request from marketplace traffic.",
        first_artifact=".tmp/non-bounty/402_rest_publish_plan.json",
        next_machine_step="Mirror the current x402 discovery data into a 402.rest publisher-ready service description.",
        why_agent_fits="x0tta6bl4 already has small JSON tools with public endpoints and clear per-call prices.",
        zero_budget_note="No new model spend is needed for the product; publisher onboarding and traffic remain external gates.",
        gates=("publisher_onboarding", "service_review_or_indexing", "buyer_call", "x402_payment"),
        risks=("registration_gate", "buyer_demand_unknown", "unverified_first_sale_to_this_wallet"),
        repo_assets=("src/sales/x402_paid_api.py", ".tmp/non-bounty/x402_paid_api_public_discovery_current.json"),
        source_urls=("https://www.402.rest/",),
        cash_speed=5,
        zero_budget_fit=8,
        automation_fit=9,
        payout_clarity=8,
        token_efficiency=8,
        market_validation=7,
    ),
    IncomeOpportunity(
        opportunity_id="agent_bazaar_skill_listing",
        title="Agent Bazaar x402 skill listing",
        channel="agent skill marketplace",
        revenue_model="List one narrow x402 API skill and earn per paid call.",
        first_artifact=".tmp/non-bounty/agent_bazaar_skill_submission.json",
        next_machine_step="Prepare a skill listing for domain-health, URL snapshot, or CI/CD pipeline generator endpoints.",
        why_agent_fits="The current x0tta6bl4 public API already exposes machine-readable paid endpoints that match Agent Bazaar skill categories.",
        zero_budget_note="No new model or cloud spend is needed; marketplace review and buyer traffic are external gates.",
        gates=("skill_submission", "review_within_platform_window", "buyer_call", "x402_payment"),
        risks=("manual_form_or_account_gate", "review_delay", "unverified_first_sale_to_this_wallet"),
        repo_assets=("src/sales/x402_paid_api.py", ".tmp/non-bounty/x402_paid_api_public_discovery_current.json"),
        source_urls=("https://agent-bazaar.com/dev", "https://agent-bazaar.com/marketplace"),
        cash_speed=5,
        zero_budget_fit=8,
        automation_fit=9,
        payout_clarity=8,
        token_efficiency=9,
        market_validation=7,
    ),
    IncomeOpportunity(
        opportunity_id="molted_work_agent",
        title="Molted worker agent",
        channel="agent task marketplace",
        revenue_model="Bid on jobs and receive USDC on Base after accepted completion.",
        first_artifact=".tmp/non-bounty/molted_worker_probe.json",
        next_machine_step="Probe Molted job discovery daily; register only if open jobs are visible through API or CLI.",
        why_agent_fits="x0tta6bl4 can deliver small public-input data, docs, API, and code artifacts.",
        zero_budget_note="Registration is advertised as CLI/API-driven, but live job API currently needs verification before spending tokens.",
        gates=("agent_registration", "open_job_visibility", "accepted_bid", "completion_approval"),
        risks=("api_probe_currently_404", "buyer_acceptance_required", "unverified_first_sale_to_this_wallet"),
        repo_assets=("scripts/ops/run_non_bounty_scout.py", "src/sales/non_bounty_task_scout.py"),
        source_urls=("https://molted.work/",),
        cash_speed=4,
        zero_budget_fit=7,
        automation_fit=8,
        payout_clarity=8,
        token_efficiency=7,
        market_validation=6,
    ),
    IncomeOpportunity(
        opportunity_id="stackstasker_stx_tasks",
        title="StacksTasker STX tasks",
        channel="agent task marketplace",
        revenue_model="Bid on public tasks and receive STX through an x402-style flow.",
        first_artifact=".tmp/non-bounty/stackstasker_task_probe.json",
        next_machine_step="Watch only; use it if Base-USDC routes dry up and STX payout handling is added.",
        why_agent_fits="The visible tasks include research, data pipeline, scraping, monitoring, and API integration work.",
        zero_budget_note="No upfront money is visible for browsing, but payout is not to the current Base wallet.",
        gates=("stx_wallet", "agent_registration", "accepted_bid", "stx_settlement"),
        risks=("not_base_wallet_direct", "public_api_currently_404", "new_marketplace"),
        repo_assets=("scripts/ops/run_non_bounty_scout.py",),
        source_urls=("https://stackstasker.com/",),
        cash_speed=3,
        zero_budget_fit=7,
        automation_fit=7,
        payout_clarity=6,
        token_efficiency=7,
        market_validation=5,
    ),
    IncomeOpportunity(
        opportunity_id="bothire_x402_bot",
        title="BotHire x402 bot",
        channel="machine-first bot marketplace",
        revenue_model="Register a bot skill and receive USDC on Base through x402 calls.",
        first_artifact=".tmp/non-bounty/bothire_bot_profile.json",
        next_machine_step="Expose the current repo-triage and API-docs endpoints as machine-readable bot skills.",
        why_agent_fits="The product pitch is bot-to-bot negotiation and payment; x0tta6bl4 already exposes paid tools.",
        zero_budget_note="No new compute path is needed, but live registration/API path still needs verification.",
        gates=("registration", "machine_readable_docs", "buyer_call", "onchain_payment"),
        risks=("public_registration_unverified", "new_marketplace", "needs_discovery"),
        repo_assets=("src/sales/x402_paid_api.py", "scripts/ops/non_bounty_market_matrix.py"),
        source_urls=("https://www.bothire.io/",),
        cash_speed=5,
        zero_budget_fit=7,
        automation_fit=9,
        payout_clarity=8,
        token_efficiency=8,
        market_validation=6,
    ),
    IncomeOpportunity(
        opportunity_id="workusdc_micro_contracts",
        title="WorkUSDC micro contracts",
        channel="crypto freelance marketplace",
        revenue_model="Submit proposals to USDC-funded work and receive payouts through Base USDC escrow.",
        first_artifact=".tmp/non-bounty/workusdc_market_probe.json",
        next_machine_step="Watch only until the wallet has seed USDC; proposal submission itself costs 2 USDC.",
        why_agent_fits="The best-fit tasks are small public-input Python, API docs, data, and QA deliverables.",
        zero_budget_note="Bad first-money route because freelancer proposals require upfront USDC credit.",
        gates=("account_registration", "proposal_credit_2_usdc", "client_hire", "escrow_release"),
        risks=("requires_upfront_usdc", "cyber_work_compliance_gate", "buyer_acceptance_required"),
        repo_assets=("scripts/ops/run_non_bounty_scout.py", "src/sales/non_bounty_task_scout.py"),
        source_urls=("https://workusdc.com/",),
        cash_speed=2,
        zero_budget_fit=2,
        automation_fit=6,
        payout_clarity=7,
        token_efficiency=4,
        market_validation=5,
    ),
    IncomeOpportunity(
        opportunity_id="io_net_worker_rewards",
        title="io.net worker rewards",
        channel="DePIN compute",
        revenue_model="Supply CPU/GPU compute and receive IO Coin earnings or rewards if the worker is eligible.",
        first_artifact=".tmp/non-bounty/io_net_worker_probe.json",
        next_machine_step="Check local hardware eligibility only; do not install worker software until payout and staking requirements are verified.",
        why_agent_fits="x0tta6bl4 can monitor uptime, utilization, and job health, but the earning unit is hardware, not prompts.",
        zero_budget_note="Potentially zero cash if idle hardware qualifies; staking, wallet, and account gates may still block earnings.",
        gates=("supported_hardware", "account_wallet_link", "worker_eligibility", "withdrawal"),
        risks=("hardware_required", "staking_or_account_gate", "not_target_base_wallet_direct"),
        repo_assets=("src/monitoring/production_monitoring.py",),
        source_urls=("https://io.net/docs/guides/workers/rewards-wallets",),
        cash_speed=2,
        zero_budget_fit=6,
        automation_fit=7,
        payout_clarity=7,
        token_efficiency=6,
        market_validation=8,
    ),
    IncomeOpportunity(
        opportunity_id="akash_homenode_provider",
        title="Akash Homenode provider",
        channel="DePIN compute",
        revenue_model="Offer GPU compute to Akash demand and earn from hosted inference workloads if hardware is accepted.",
        first_artifact=".tmp/non-bounty/akash_homenode_probe.json",
        next_machine_step="Park unless a supported GPU is present; this is a hardware route, not a token-only route.",
        why_agent_fits="x0tta6bl4 can wrap provider health, uptime, and pricing telemetry around an accepted node.",
        zero_budget_note="No point spending tokens if there is no supported GPU or provider onboarding path.",
        gates=("supported_gpu", "provider_onboarding", "workload_demand", "settlement"),
        risks=("hardware_required", "beta_or_waitlist_gate", "not_instant_cash"),
        repo_assets=("src/monitoring/production_monitoring.py", "src/swarm/agents/pricing_agent.py"),
        source_urls=("https://akash.network/blog/akash-network-q1-2026-report/", "https://akash.network/docs/providers/getting-started/should-i-run-a-provider/"),
        cash_speed=2,
        zero_budget_fit=5,
        automation_fit=7,
        payout_clarity=6,
        token_efficiency=5,
        market_validation=8,
    ),
    IncomeOpportunity(
        opportunity_id="bless_edge_node",
        title="Bless edge compute node",
        channel="DePIN compute",
        revenue_model="Contribute idle CPU/GPU or browser node resources and earn network rewards if eligible.",
        first_artifact=".tmp/non-bounty/bless_node_probe.json",
        next_machine_step="Treat as passive watchlist; verify eligibility and payout terms before installing node software.",
        why_agent_fits="x0tta6bl4 can monitor uptime and resource health, but this is infrastructure contribution, not task execution.",
        zero_budget_note="Potentially uses idle hardware, but rewards and withdrawal terms must be verified before counting money.",
        gates=("node_install", "eligibility", "uptime", "reward_conversion_or_withdrawal"),
        risks=("unclear_immediate_cash", "hardware_and_bandwidth_cost", "jurisdiction_or_account_gate"),
        repo_assets=("src/services/share_to_earn_service.py", "src/monitoring/production_monitoring.py"),
        source_urls=("https://docs.bless.network/",),
        cash_speed=2,
        zero_budget_fit=7,
        automation_fit=7,
        payout_clarity=4,
        token_efficiency=7,
        market_validation=5,
    ),
    IncomeOpportunity(
        opportunity_id="nodepay_signal_rewards",
        title="Nodepay signal rewards",
        channel="data contribution rewards",
        revenue_model="Contribute human/input signals or network data to earn platform rewards.",
        first_artifact=".tmp/non-bounty/nodepay_signal_probe.json",
        next_machine_step="Do not prioritize for autonomous earning; monitor only if a legitimate agent-safe API/workflow appears.",
        why_agent_fits="The platform rewards contributors, but the official description is human-signal oriented, not autonomous agent work.",
        zero_budget_note="May not need upfront money, but reward-to-wallet path is not verified for this agent.",
        gates=("account_registration", "eligible_contribution", "reward_rules", "withdrawal"),
        risks=("not_agent_direct", "points_or_rewards_not_cash", "account_gate"),
        repo_assets=("scripts/ops/non_bounty_market_matrix.py",),
        source_urls=("https://docs.nodepay.ai/",),
        cash_speed=1,
        zero_budget_fit=6,
        automation_fit=3,
        payout_clarity=3,
        token_efficiency=3,
        market_validation=5,
    ),
    IncomeOpportunity(
        opportunity_id="gradient_sentry_rewards",
        title="Gradient Sentry rewards",
        channel="DePIN compute",
        revenue_model="Legacy uptime/tap/referral rewards for Sentry Nodes.",
        first_artifact=".tmp/non-bounty/gradient_sentry_probe.json",
        next_machine_step="Park this route; official docs say Sentry Node rewards do not currently pay.",
        why_agent_fits="x0tta6bl4 can run uptime infrastructure, but there is no current reward to harvest here.",
        zero_budget_note="Zero-budget does not help if the official reward window is concluded.",
        gates=("future_season", "node_eligibility", "reward_rules", "withdrawal"),
        risks=("official_rewards_concluded", "no_current_cash", "sybil_policy"),
        repo_assets=("src/monitoring/production_monitoring.py",),
        source_urls=("https://docs.gradient.network/rewards",),
        cash_speed=0,
        zero_budget_fit=6,
        automation_fit=6,
        payout_clarity=1,
        token_efficiency=2,
        market_validation=4,
    ),
    IncomeOpportunity(
        opportunity_id="clawmart_skill_listing",
        title="ClawMart skill listing",
        channel="agent skill marketplace",
        revenue_model="Package a narrow paid developer-assistant role as a reusable agent skill.",
        first_artifact=".tmp/non-bounty/clawmart_skill_listing.json",
        next_machine_step="Turn the API-docs endpoint into a fixed role: 'API docs in Markdown from JSON specs'.",
        why_agent_fits="ClawMart sells scoped agent roles; x0tta6bl4 can expose a bounded skill with clear output.",
        zero_budget_note="Reuse the current endpoint; onboarding and marketplace demand are external gates.",
        gates=("seller_onboarding", "skill_review", "buyer_subscription_or_call", "payout_setup"),
        risks=("not_verified_as_open_self_serve", "less_direct_than_x402", "needs_positioning"),
        repo_assets=("src/sales/x402_paid_api.py", "docs/commercial/NON_BOUNTY_INCOME_MAP.md"),
        source_urls=("https://clawmart.co/",),
        cash_speed=4,
        zero_budget_fit=6,
        automation_fit=8,
        payout_clarity=6,
        token_efficiency=7,
        market_validation=6,
    ),
    IncomeOpportunity(
        opportunity_id="clawdgigs_fixed_gig",
        title="ClawdGigs fixed x402 gig",
        channel="agent gig marketplace",
        revenue_model="Fixed-scope gig with x402 escrow; deliver one artifact, wait for release.",
        first_artifact=".tmp/non-bounty/clawdgigs_fixed_gig.json",
        next_machine_step="Create a fixed 3 USDC gig: API docs from endpoint JSON, delivered as Markdown.",
        why_agent_fits="Fixed deliverables reduce ambiguity and token waste; x0tta6bl4 already has the generator.",
        zero_budget_note="Offer creation may be free; escrow release and buyer demand are external gates.",
        gates=("agent_registration", "gig_publication", "buyer_acceptance", "escrow_release"),
        risks=("external_account_gate", "buyer_demand_unknown", "dispute_or_acceptance_delay"),
        repo_assets=("src/sales/x402_paid_api.py", "scripts/ops/non_bounty_market_matrix.py"),
        source_urls=("https://www.clawdgigs.com/",),
        cash_speed=4,
        zero_budget_fit=7,
        automation_fit=8,
        payout_clarity=7,
        token_efficiency=8,
        market_validation=6,
    ),
    IncomeOpportunity(
        opportunity_id="clawgig_agent_freelancer",
        title="ClawGig agent freelancer",
        channel="agent freelance marketplace",
        revenue_model="USDC escrow; platform page says agent keeps 90 percent.",
        first_artifact=".tmp/non-bounty/clawgig_agent_profile.json",
        next_machine_step="Prepare a low-risk agent profile and skill list for research, data, Python, and code review gigs.",
        why_agent_fits="The site describes REST/MCP flows for browsing gigs, proposals, delivery, and payout.",
        zero_budget_note="Registration may be free, but the current public page showed zero users and zero earnings.",
        gates=("agent_registration", "api_key", "accepted_proposal", "escrow_release"),
        risks=("market_appears_empty", "unproven_demand", "external_account_gate"),
        repo_assets=("scripts/ops/run_paid_task_watch_loop.py", "src/sales/product_ideas.py"),
        source_urls=("https://clawgig.ai/",),
        cash_speed=5,
        zero_budget_fit=8,
        automation_fit=9,
        payout_clarity=8,
        token_efficiency=7,
        market_validation=2,
    ),
    IncomeOpportunity(
        opportunity_id="apify_affiliate_content_engine",
        title="Apify affiliate content engine",
        channel="affiliate",
        revenue_model="Recurring commission from referred Apify customers.",
        first_artifact=".tmp/non-bounty/apify_affiliate_content_plan.json",
        next_machine_step="Generate search-targeted pages/tutorials around scraping workflows and x0tta6bl4 actors.",
        why_agent_fits="Agent can create tutorials, examples, comparison pages, and update them automatically.",
        zero_budget_note="Content can be generated locally; payout needs affiliate approval and PayPal/bank details.",
        gates=("affiliate_approval", "audience_or_seo_traffic", "minimum_payout", "payout_method"),
        risks=("slow_cash", "needs_distribution", "paid_ads_forbidden_by_program"),
        repo_assets=("docs/commercial/PRODUCT_IDEA_PORTFOLIO.md", "src/sales/product_ideas.py"),
        source_urls=("https://apify.com/partners/affiliate",),
        cash_speed=2,
        zero_budget_fit=8,
        automation_fit=7,
        payout_clarity=8,
        token_efficiency=6,
        market_validation=8,
    ),
    IncomeOpportunity(
        opportunity_id="telegram_stars_microtools",
        title="Telegram Stars microtools",
        channel="consumer bot",
        revenue_model="Small paid Telegram Stars actions.",
        first_artifact=".tmp/non-bounty/telegram_microtool_menu.json",
        next_machine_step="Package one narrow tool: voice summary, document draft, or public-page digest.",
        why_agent_fits="Agent can process user input and return a finished result after payment.",
        zero_budget_note="Bot can run locally; demand acquisition is the hard part.",
        gates=("bot_token", "telegram_stars_setup", "users", "withdrawal_eligibility"),
        risks=("user_acquisition", "support_load", "user_already_rejected_as_uninteresting"),
        repo_assets=("src/sales/telegram_bot.py", "src/sales/telegram_bot_v2.py"),
        source_urls=("https://core.telegram.org/bots/payments-stars",),
        cash_speed=3,
        zero_budget_fit=8,
        automation_fit=7,
        payout_clarity=7,
        token_efficiency=5,
        market_validation=5,
    ),
)


WEIGHTS = {
    "cash_speed": 0.24,
    "zero_budget_fit": 0.18,
    "automation_fit": 0.18,
    "payout_clarity": 0.16,
    "token_efficiency": 0.14,
    "market_validation": 0.10,
}


def score_opportunity(opportunity: IncomeOpportunity) -> dict[str, Any]:
    components = {
        "cash_speed": opportunity.cash_speed,
        "zero_budget_fit": opportunity.zero_budget_fit,
        "automation_fit": opportunity.automation_fit,
        "payout_clarity": opportunity.payout_clarity,
        "token_efficiency": opportunity.token_efficiency,
        "market_validation": opportunity.market_validation,
    }
    score = round(sum(components[key] * WEIGHTS[key] * 10 for key in components), 1)
    if score >= 72:
        decision = "take_first"
    elif score >= 58:
        decision = "manual_review"
    else:
        decision = "park"
    return {
        "opportunity_id": opportunity.opportunity_id,
        "title": opportunity.title,
        "channel": opportunity.channel,
        "revenue_model": opportunity.revenue_model,
        "score": score,
        "decision": decision,
        "components": components,
        "first_artifact": opportunity.first_artifact,
        "next_machine_step": opportunity.next_machine_step,
        "why_agent_fits": opportunity.why_agent_fits,
        "zero_budget_note": opportunity.zero_budget_note,
        "gates": list(opportunity.gates),
        "risks": list(opportunity.risks),
        "repo_assets": list(opportunity.repo_assets),
        "source_urls": list(opportunity.source_urls),
    }


def _asset_status(root: Path, paths: tuple[str, ...]) -> list[dict[str, Any]]:
    return [{"path": path, "exists": (root / path).exists()} for path in paths]


def build_non_bounty_income_map(root: Path | str = ".") -> dict[str, Any]:
    root_path = Path(root)
    ranked = sorted(
        (score_opportunity(opportunity) for opportunity in OPPORTUNITIES),
        key=lambda item: (item["score"], item["title"]),
        reverse=True,
    )
    for item in ranked:
        source = next(opportunity for opportunity in OPPORTUNITIES if opportunity.opportunity_id == item["opportunity_id"])
        item["asset_status"] = _asset_status(root_path, source.repo_assets)
    selected = [item for item in ranked if item["decision"] == "take_first"][:3]
    return {
        "schema": SCHEMA,
        "status": "map_ready",
        "claim_boundary": CLAIM_BOUNDARY,
        "thinking_contract": {
            "first_principles": (
                "Real money requires buyer, deliverable, acceptance rule, settlement path, and proof."
            ),
            "reverse_planning": (
                "Start from confirmed payout, work backward to accepted delivery, accepted offer, account gate, and first artifact."
            ),
            "scamper": (
                "Reuse bounty filters as paid APIs, adapt product ideas into Actors, combine reports with agent marketplaces."
            ),
            "mapek": (
                "Monitor sources, analyze clean opportunities, plan one artifact, execute only one route, record outcomes."
            ),
            "weighted_matrix": WEIGHTS,
        },
        "selected_first": selected,
        "ranked": ranked,
        "claim_gate": {
            "analysis_claim_allowed": True,
            "funds_received_claim_allowed": False,
            "accepted_work_claim_allowed": False,
            "external_account_access_claim_allowed": False,
        },
    }
