apiVersion: v2
name: mtls-optimization
description: Оптимизированный mTLS с session resumption и certificate pinning для критических сервисов
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - mtls
  - tls
  - security
  - session-resumption
  - certificate-pinning
  - performance
home: https://github.com/x0tta6bl4/infrastructure-optimizations
maintainers:
  - name: x0tta6bl4
dependencies:
  - name: cert-manager
    version: "1.13.0"
    repository: "https://charts.jetstack.io"