apiVersion: v1
kind: Service
metadata:
  name: x0tta6bl4
  namespace: x0tta6bl4-staging
  labels:
    app.kubernetes.io/instance: x0tta6bl4
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: x0tta6bl4
    app.kubernetes.io/version: "3.4.0"
    helm.sh/chart: x0tta6bl4-3.4.0
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/instance: x0tta6bl4
    app.kubernetes.io/name: x0tta6bl4
