"""Registry of event-producing services and trace-visible source agents."""

from __future__ import annotations

from typing import Dict, List, Tuple

from src.services.service_event_identity import service_event_identity_status


IDENTITY_STATUS_CLAIM_BOUNDARY = (
    "Configuration presence only. The status surface reports whether identity "
    "fields are configured and which environment tier supplied them; it does "
    "not expose SPIFFE IDs, DIDs, wallet addresses, or prove live SPIRE/chain state."
)

KNOWN_EVENT_IDENTITY_SERVICES: Tuple[Dict[str, str], ...] = (
    {
        "service_name": "maas-governance",
        "layer": "api_to_control_plane",
        "entrypoint": "src/api/maas_governance.py",
    },
    {
        "service_name": "vpn-api-status-read",
        "layer": "api_vpn_status_observed_state",
        "entrypoint": "src/api/vpn.py",
    },
    {
        "service_name": "vpn-experimental-config-generate",
        "layer": "api_vpn_experimental_config_control_action",
        "entrypoint": "src/api/vpn_experimental.py",
    },
    {
        "service_name": "vpn-experimental-status-read",
        "layer": "api_vpn_experimental_status_observed_state",
        "entrypoint": "src/api/vpn_experimental.py",
    },
    {
        "service_name": "vpn-experimental-users-read",
        "layer": "api_vpn_experimental_users_observed_state",
        "entrypoint": "src/api/vpn_experimental.py",
    },
    {
        "service_name": "vpn-experimental-user-delete",
        "layer": "api_vpn_experimental_user_delete_control_action",
        "entrypoint": "src/api/vpn_experimental.py",
    },
    {
        "service_name": "vpn-provisioning-service",
        "layer": "service_vpn_provisioning_control_action",
        "entrypoint": "src/services/provisioning_service.py",
    },
    {
        "service_name": "dao-executor",
        "layer": "dao_to_control_plane",
        "entrypoint": "src/dao/executor_webhook.py",
    },
    {
        "service_name": "dao-governance",
        "layer": "dao_to_control_plane",
        "entrypoint": "src/dao/governance.py",
    },
    {
        "service_name": "governance-contract",
        "layer": "dao_to_chain_control",
        "entrypoint": "src/dao/governance_contract.py",
    },
    {
        "service_name": "dao-proposal-executor",
        "layer": "dao_to_control_plane",
        "entrypoint": "src/dao/proposal_executor_webhook.py",
    },
    {
        "service_name": "token-bridge",
        "layer": "dao_chain_bridge",
        "entrypoint": "src/dao/token_bridge.py",
    },
    {
        "service_name": "mesh-vpn-bridge",
        "layer": "network_to_rewards",
        "entrypoint": "src/network/mesh_vpn_bridge.py",
    },
    {
        "service_name": "tun-interface",
        "layer": "network_tun_interface_observed_state",
        "entrypoint": "src/network/tun_handler.py",
    },
    {
        "service_name": "network-self-healing-daemon",
        "layer": "network_self_healing_daemon_observed_state",
        "entrypoint": "src/network/self_healing_daemon.py",
    },
    {
        "service_name": "vpn-watchdog",
        "layer": "network_vpn_watchdog_observed_state",
        "entrypoint": "src/network/vpn_watchdog.py",
    },
    {
        "service_name": "vpn-leak-protector",
        "layer": "network_vpn_leak_protection_observed_state",
        "entrypoint": "src/network/vpn_leak_protection.py",
    },
    {
        "service_name": "doh-resolver",
        "layer": "network_dns_over_https_observed_state",
        "entrypoint": "src/network/dns_over_https.py",
    },
    {
        "service_name": "network-obfuscation-transport",
        "layer": "network_obfuscation_transport_local_evidence",
        "entrypoint": "src/network/obfuscation/base.py",
    },
    {
        "service_name": "vpn-obfuscation-manager",
        "layer": "network_vpn_obfuscation_local_evidence",
        "entrypoint": "src/network/vpn_obfuscation_manager.py",
    },
    {
        "service_name": "obfuscated-socks5-proxy",
        "layer": "network_obfuscated_socks5_proxy_local_evidence",
        "entrypoint": "src/network/obfuscated_socks5.py",
    },
    {
        "service_name": "faketls-transport",
        "layer": "network_faketls_transport_local_evidence",
        "entrypoint": "src/network/obfuscation/faketls.py",
    },
    {
        "service_name": "traffic-shaper",
        "layer": "network_traffic_shaping_local_evidence",
        "entrypoint": "src/network/obfuscation/traffic_shaping.py",
    },
    {
        "service_name": "domain-fronting-transport",
        "layer": "network_domain_fronting_transport_local_evidence",
        "entrypoint": "src/network/obfuscation/domain_fronting.py",
    },
    {
        "service_name": "http-steganography-transport",
        "layer": "network_http_steganography_local_evidence",
        "entrypoint": "src/network/obfuscation/http_steganography.py",
    },
    {
        "service_name": "anti-censorship-stego-mesh",
        "layer": "anti_censorship_stego_mesh_local_evidence",
        "entrypoint": "src/anti_censorship/stego_mesh.py",
    },
    {
        "service_name": "anti-censorship-steganography-engine",
        "layer": "anti_censorship_steganography_local_evidence",
        "entrypoint": "src/anti_censorship/steganography.py",
    },
    {
        "service_name": "anti-censorship-traffic-obfuscator",
        "layer": "anti_censorship_traffic_obfuscation_local_evidence",
        "entrypoint": "src/anti_censorship/obfuscation.py",
    },
    {
        "service_name": "anti-censorship-geneva-optimizer",
        "layer": "anti_censorship_geneva_optimizer_local_evidence",
        "entrypoint": "src/anti_censorship/geneva_genetic.py",
    },
    {
        "service_name": "anti-censorship-censorship-detector",
        "layer": "anti_censorship_censorship_detector_local_evidence",
        "entrypoint": "src/anti_censorship/censorship_detector.py",
    },
    {
        "service_name": "anti-censorship-pluggable-transport",
        "layer": "anti_censorship_pluggable_transport_local_evidence",
        "entrypoint": "src/anti_censorship/transports.py",
    },
    {
        "service_name": "anti-censorship-domain-fronting-client",
        "layer": "anti_censorship_domain_fronting_local_evidence",
        "entrypoint": "src/anti_censorship/domain_fronting.py",
    },
    {
        "service_name": "shadowsocks-transport",
        "layer": "network_shadowsocks_transport_local_evidence",
        "entrypoint": "src/network/obfuscation/shadowsocks.py",
    },
    {
        "service_name": "mptcp-manager",
        "layer": "network_to_control_plane",
        "entrypoint": "src/network/mptcp_manager.py",
    },
    {
        "service_name": "proxy-orchestrator",
        "layer": "network_proxy_orchestrator_observed_state",
        "entrypoint": "src/network/proxy_orchestrator.py",
    },
    {
        "service_name": "proxy-metrics-collector",
        "layer": "network_proxy_metrics_observed_state",
        "entrypoint": "src/network/proxy_metrics_collector.py",
    },
    {
        "service_name": "proxy-control-plane",
        "layer": "network_proxy_control_plane_observed_state",
        "entrypoint": "src/network/proxy_control_plane.py",
    },
    {
        "service_name": "geo-proxy-shard-manager",
        "layer": "network_geo_proxy_sharding_observed_state",
        "entrypoint": "src/network/geo_proxy_sharding.py",
    },
    {
        "service_name": "proxy-selection-algorithm",
        "layer": "network_proxy_selection_observed_state",
        "entrypoint": "src/network/proxy_selection_algorithm.py",
    },
    {
        "service_name": "reputation-scoring-system",
        "layer": "network_reputation_scoring_observed_state",
        "entrypoint": "src/network/reputation_scoring.py",
    },
    {
        "service_name": "residential-proxy-manager",
        "layer": "network_residential_proxy_manager_observed_state",
        "entrypoint": "src/network/residential_proxy_manager.py",
    },
    {
        "service_name": "yggdrasil-client",
        "layer": "network_yggdrasil_observed_state",
        "entrypoint": "src/network/yggdrasil_client.py",
    },
    {
        "service_name": "real-network-adapter",
        "layer": "mesh_real_network_observed_state",
        "entrypoint": "src/mesh/real_network_adapter.py",
    },
    {
        "service_name": "mesh-network-manager",
        "layer": "mesh_network_manager_observed_state",
        "entrypoint": "src/mesh/network_manager.py",
    },
    {
        "service_name": "mesh-action-enforcer",
        "layer": "mesh_action_enforcer_control_action",
        "entrypoint": "src/mesh/action_enforcer.py",
    },
    {
        "service_name": "mesh-yggdrasil-optimizer",
        "layer": "mesh_yggdrasil_optimizer_observed_state",
        "entrypoint": "src/mesh/yggdrasil_optimizer.py",
    },
    {
        "service_name": "mesh-telemetry-collector",
        "layer": "mesh_telemetry_collector_observed_state",
        "entrypoint": "src/mesh/telemetry_collector.py",
    },
    {
        "service_name": "batman-optimizations",
        "layer": "network_batman_optimizations_observed_state",
        "entrypoint": "src/network/batman/optimizations.py",
    },
    {
        "service_name": "ebpf-dynamic-fallback",
        "layer": "network_ebpf_fallback_observed_state",
        "entrypoint": "src/network/ebpf/dynamic_fallback.py",
    },
    {
        "service_name": "ebpf-bcc-probes",
        "layer": "network_ebpf_bcc_probes_observed_state",
        "entrypoint": "src/network/ebpf/bcc_probes.py",
    },
    {
        "service_name": "ebpf-profiler",
        "layer": "network_ebpf_profiler_observed_state",
        "entrypoint": "src/network/ebpf/profiler.py",
    },
    {
        "service_name": "ebpf-mesh-integration",
        "layer": "network_ebpf_mesh_integration_observed_state",
        "entrypoint": "src/network/ebpf/mesh_integration.py",
    },
    {
        "service_name": "ebpf-rate-limiter-manager",
        "layer": "network_ebpf_rate_limiter_observed_state",
        "entrypoint": "src/network/ebpf/rate_limiter_manager.py",
    },
    {
        "service_name": "ebpf-loader",
        "layer": "network_ebpf_loader_observed_state",
        "entrypoint": "src/network/ebpf/ebpf_loader.py",
    },
    {
        "service_name": "ebpf-loader-implementation",
        "layer": "network_ebpf_loader_implementation_observed_state",
        "entrypoint": "src/network/ebpf/loader_implementation.py",
    },
    {
        "service_name": "ebpf-legacy-loader",
        "layer": "network_ebpf_legacy_loader_observed_state",
        "entrypoint": "src/network/ebpf/loader/_legacy.py",
    },
    {
        "service_name": "ebpf-loader-map-manager",
        "layer": "network_ebpf_loader_map_manager_observed_state",
        "entrypoint": "src/network/ebpf/loader/map_manager.py",
    },
    {
        "service_name": "ebpf-loader-program-loader",
        "layer": "network_ebpf_loader_program_loader_observed_state",
        "entrypoint": "src/network/ebpf/loader/program_loader.py",
    },
    {
        "service_name": "ebpf-loader-attach-manager",
        "layer": "network_ebpf_loader_attach_manager_observed_state",
        "entrypoint": "src/network/ebpf/loader/attach_manager.py",
    },
    {
        "service_name": "ebpf-xdp-hook",
        "layer": "network_ebpf_xdp_hook_observed_state",
        "entrypoint": "src/network/ebpf/hooks/xdp_hook.py",
    },
    {
        "service_name": "pqc-xdp-loader",
        "layer": "network_ebpf_pqc_xdp_loader_observed_state",
        "entrypoint": "src/network/ebpf/pqc_xdp_loader.py",
    },
    {
        "service_name": "pqc-verification-daemon",
        "layer": "network_ebpf_pqc_verification_observed_state",
        "entrypoint": "src/network/ebpf/pqc_verification_daemon.py",
    },
    {
        "service_name": "pqc-quarantine-manager",
        "layer": "network_ebpf_pqc_quarantine_observed_state",
        "entrypoint": "src/network/ebpf/quarantine_manager.py",
    },
    {
        "service_name": "ebpf-attestation-map-manager",
        "layer": "network_ebpf_attestation_map_observed_state",
        "entrypoint": "src/network/ebpf/map_manager.py",
    },
    {
        "service_name": "ebpf-map-reader",
        "layer": "network_ebpf_map_reader_observed_state",
        "entrypoint": "src/network/ebpf/telemetry/map_reader.py",
    },
    {
        "service_name": "ebpf-telemetry-module",
        "layer": "network_ebpf_telemetry_module_observed_state",
        "entrypoint": "src/network/ebpf/telemetry_module.py",
    },
    {
        "service_name": "ebpf-bpftool-map-reader",
        "layer": "network_ebpf_bpftool_map_reader_observed_state",
        "entrypoint": "src/network/ebpf/map_reader.py",
    },
    {
        "service_name": "ebpf-ringbuf-reader",
        "layer": "network_ebpf_ringbuf_observed_state",
        "entrypoint": "src/network/ebpf/ringbuf_reader.py",
    },
    {
        "service_name": "ebpf-metrics-exporter",
        "layer": "network_ebpf_metrics_observed_state",
        "entrypoint": "src/network/ebpf/metrics_exporter.py",
    },
    {
        "service_name": "ebpf-metrics-exporter-enhanced",
        "layer": "network_ebpf_metrics_enhanced_observed_state",
        "entrypoint": "src/network/ebpf/metrics_exporter_enhanced.py",
    },
    {
        "service_name": "ebpf-stigmergy-loader",
        "layer": "network_ebpf_stigmergy_loader_observed_state",
        "entrypoint": "src/network/ebpf/stigmergy_loader.py",
    },
    {
        "service_name": "ebpf-stigmergy-bridge",
        "layer": "network_ebpf_stigmergy_observed_state",
        "entrypoint": "src/network/ebpf/stigmergy_bridge.py",
    },
    {
        "service_name": "core-mapek-loop",
        "layer": "core_mapek_control_spine",
        "entrypoint": "src/core/mape_k_loop.py",
    },
    {
        "service_name": "spire-agent-manager",
        "layer": "security_identity_to_control_plane",
        "entrypoint": "src/security/spiffe/agent/manager.py",
    },
    {
        "service_name": "spire-server-client",
        "layer": "security_identity_to_control_plane",
        "entrypoint": "src/security/spiffe/server/client.py",
    },
    {
        "service_name": "spiffe-workload-api",
        "layer": "security_workload_identity_observed_state",
        "entrypoint": "src/security/spiffe/workload/api_client.py",
    },
    {
        "service_name": "ebpf-self-healing",
        "layer": "self_healing_to_control_plane",
        "entrypoint": "src/self_healing/ebpf_anomaly_detector.py",
    },
    {
        "service_name": "self-healing-mapek",
        "layer": "self_healing_mapek_control_spine",
        "entrypoint": "src/self_healing/mape_k/manager.py",
    },
    {
        "service_name": "spiffe-mapek-loop",
        "layer": "self_healing_identity_loop",
        "entrypoint": "src/self_healing/mape_k_spiffe_integration.py",
    },
    {
        "service_name": "pqc-zero-trust-executor",
        "source_agent": "pqc-zero-trust-healer",
        "layer": "self_healing_pqc_identity",
        "entrypoint": "src/self_healing/pqc_zero_trust_healer.py",
    },
    {
        "service_name": "recovery-action-executor",
        "layer": "self_healing_to_control_plane",
        "entrypoint": "src/self_healing/recovery/executor.py",
    },
    {
        "service_name": "ghost-l3-server",
        "layer": "server_to_control_plane",
        "entrypoint": "src/server/ghost_server.py",
    },
    {
        "service_name": "maas-janitor",
        "layer": "commerce_maintenance_to_events",
        "entrypoint": "src/services/marketplace_janitor.py",
    },
    {
        "service_name": "maas-settlement",
        "layer": "commerce_settlement_to_events",
        "entrypoint": "src/services/marketplace_settlement.py",
    },
    {
        "service_name": "pqc-rotator",
        "layer": "security_service_to_control_plane",
        "entrypoint": "src/services/pqc_rotator_service.py",
    },
    {
        "service_name": "share-to-earn",
        "layer": "network_usage_to_rewards",
        "entrypoint": "src/services/share_to_earn_service.py",
    },
    {
        "service_name": "swarm-mapek",
        "layer": "swarm_to_control_plane",
        "entrypoint": "src/swarm/intelligence/mapek.py",
    },
    {
        "service_name": "swarm-pbft",
        "layer": "swarm_consensus_to_control_plane",
        "entrypoint": "src/swarm/pbft.py",
    },
)

KNOWN_EVENT_TRACE_SERVICES: Tuple[Dict[str, str], ...] = (
    *KNOWN_EVENT_IDENTITY_SERVICES,
    {
        "service_name": "mptcp-manager-status-read",
        "layer": "network_mptcp_observed_state",
        "entrypoint": "src/network/mptcp_manager.py",
        "identity_source": "local_mptcp_kernel_status_read",
    },
    {
        "service_name": "maas-governance-proposal-create",
        "layer": "api_governance_proposal_control_action",
        "entrypoint": "src/api/maas_governance.py",
        "identity_source": "governance_proposal_create_request_user",
    },
    {
        "service_name": "maas-governance-vote-cast",
        "layer": "api_governance_vote_control_action",
        "entrypoint": "src/api/maas_governance.py",
        "identity_source": "governance_vote_request_user",
    },
    {
        "service_name": "maas-governance-proposal-execute",
        "layer": "api_governance_execution_control_action",
        "entrypoint": "src/api/maas_governance.py",
        "identity_source": "governance_execute_request_user",
    },
    {
        "service_name": "maas-governance-proposal-list-read",
        "layer": "api_governance_observed_state",
        "entrypoint": "src/api/maas_governance.py",
        "identity_source": "governance_proposal_list_request",
    },
    {
        "service_name": "maas-governance-proposal-read",
        "layer": "api_governance_observed_state",
        "entrypoint": "src/api/maas_governance.py",
        "identity_source": "governance_proposal_read_request",
    },
    {
        "service_name": "maas-marketplace",
        "layer": "api_to_commerce",
        "entrypoint": "src/api/maas_marketplace.py",
        "identity_source": "request_user_identity",
    },
    {
        "service_name": "maas-auth-register",
        "layer": "api_auth_registration_intent",
        "entrypoint": "src/api/maas_auth.py",
        "identity_source": "auth_register_request",
    },
    {
        "service_name": "maas-auth-login",
        "layer": "api_auth_login_intent",
        "entrypoint": "src/api/maas_auth.py",
        "identity_source": "auth_login_request",
    },
    {
        "service_name": "maas-auth-api-key-rotation",
        "layer": "api_auth_credential_rotation",
        "entrypoint": "src/api/maas_auth.py",
        "identity_source": "auth_api_key_rotation_request",
    },
    {
        "service_name": "maas-auth-admin-promotion",
        "layer": "api_auth_admin_privilege_control",
        "entrypoint": "src/api/maas_auth.py",
        "identity_source": "auth_admin_promotion_request",
    },
    {
        "service_name": "maas-auth-bootstrap-admin",
        "layer": "api_auth_bootstrap_admin_control",
        "entrypoint": "src/api/maas_auth.py",
        "identity_source": "auth_bootstrap_admin_request",
    },
    {
        "service_name": "maas-auth-oidc-login",
        "layer": "api_auth_oidc_redirect_intent",
        "entrypoint": "src/api/maas_auth.py",
        "identity_source": "auth_oidc_redirect_request",
    },
    {
        "service_name": "maas-auth-oidc-callback",
        "layer": "api_auth_oidc_callback_control",
        "entrypoint": "src/api/maas_auth.py",
        "identity_source": "auth_oidc_callback_request",
    },
    {
        "service_name": "maas-auth-credential-resolver",
        "layer": "api_auth_credential_observed_state",
        "entrypoint": "src/api/maas_auth.py",
        "identity_source": "auth_request_credentials",
    },
    {
        "service_name": "maas-auth-profile-read",
        "layer": "api_auth_profile_observed_state",
        "entrypoint": "src/api/maas_auth.py",
        "identity_source": "auth_profile_request_user",
    },
    {
        "service_name": "maas-auth-api-key-read",
        "layer": "api_auth_api_key_observed_state",
        "entrypoint": "src/api/maas_auth.py",
        "identity_source": "auth_api_key_read_request_user",
    },
    {
        "service_name": "maas-dashboard-summary-read",
        "layer": "api_dashboard_summary_observed_state",
        "entrypoint": "src/api/maas_dashboard.py",
        "identity_source": "dashboard_summary_request_user",
    },
    {
        "service_name": "maas-dashboard-analytics-read",
        "layer": "api_dashboard_analytics_observed_state",
        "entrypoint": "src/api/maas_dashboard.py",
        "identity_source": "dashboard_analytics_request_user",
    },
    {
        "service_name": "maas-dashboard-node-read",
        "layer": "api_dashboard_node_observed_state",
        "entrypoint": "src/api/maas_dashboard.py",
        "identity_source": "dashboard_nodes_request_user",
    },
    {
        "service_name": "maas-analytics-summary-read",
        "layer": "api_analytics_summary_observed_state",
        "entrypoint": "src/api/maas_analytics.py",
        "identity_source": "analytics_summary_request_user",
    },
    {
        "service_name": "maas-analytics-timeseries-read",
        "layer": "api_analytics_timeseries_observed_state",
        "entrypoint": "src/api/maas_analytics.py",
        "identity_source": "analytics_timeseries_request_user",
    },
    {
        "service_name": "maas-analytics-roi-read",
        "layer": "api_analytics_roi_observed_state",
        "entrypoint": "src/api/maas_analytics.py",
        "identity_source": "analytics_roi_request_user",
    },
    {
        "service_name": "maas-policies-list-read",
        "layer": "api_policy_acl_observed_state",
        "entrypoint": "src/api/maas_policies.py",
        "identity_source": "policy_list_request_user",
    },
    {
        "service_name": "maas-policies-create",
        "layer": "api_policy_acl_control_action",
        "entrypoint": "src/api/maas_policies.py",
        "identity_source": "policy_create_request_user",
    },
    {
        "service_name": "maas-policies-delete",
        "layer": "api_policy_acl_control_action",
        "entrypoint": "src/api/maas_policies.py",
        "identity_source": "policy_delete_request_user",
    },
    {
        "service_name": "maas-supply-chain-sbom-read",
        "layer": "api_supply_chain_sbom_observed_state",
        "entrypoint": "src/api/maas_supply_chain.py",
        "identity_source": "supply_chain_public_sbom_request",
    },
    {
        "service_name": "maas-supply-chain-sbom-list-read",
        "layer": "api_supply_chain_sbom_observed_state",
        "entrypoint": "src/api/maas_supply_chain.py",
        "identity_source": "supply_chain_public_sbom_list_request",
    },
    {
        "service_name": "maas-supply-chain-artifact-register",
        "layer": "api_supply_chain_artifact_control_action",
        "entrypoint": "src/api/maas_supply_chain.py",
        "identity_source": "supply_chain_register_request_user",
    },
    {
        "service_name": "maas-supply-chain-binary-verify",
        "layer": "api_supply_chain_binary_attestation_control",
        "entrypoint": "src/api/maas_supply_chain.py",
        "identity_source": "supply_chain_binary_verify_request",
    },
    {
        "service_name": "maas-supply-chain-node-attestation-read",
        "layer": "api_supply_chain_attestation_observed_state",
        "entrypoint": "src/api/maas_supply_chain.py",
        "identity_source": "supply_chain_node_attestation_request_user",
    },
    {
        "service_name": "maas-supply-chain-mesh-attestation-read",
        "layer": "api_supply_chain_attestation_observed_state",
        "entrypoint": "src/api/maas_supply_chain.py",
        "identity_source": "supply_chain_mesh_attestation_request_user",
    },
    {
        "service_name": "maas-playbooks-create",
        "layer": "api_playbook_signed_command_control",
        "entrypoint": "src/api/maas_playbooks.py",
        "identity_source": "playbook_create_request_user",
    },
    {
        "service_name": "maas-playbooks-poll",
        "layer": "api_playbook_signed_command_dispatch",
        "entrypoint": "src/api/maas_playbooks.py",
        "identity_source": "playbook_node_poll_request",
    },
    {
        "service_name": "maas-playbooks-ack",
        "layer": "api_playbook_ack_control",
        "entrypoint": "src/api/maas_playbooks.py",
        "identity_source": "playbook_node_ack_request",
    },
    {
        "service_name": "maas-playbooks-list-read",
        "layer": "api_playbook_observed_state",
        "entrypoint": "src/api/maas_playbooks.py",
        "identity_source": "playbook_list_request_user",
    },
    {
        "service_name": "maas-playbooks-status-read",
        "layer": "api_playbook_observed_state",
        "entrypoint": "src/api/maas_playbooks.py",
        "identity_source": "playbook_status_request_user",
    },
    {
        "service_name": "maas-compat-audit-read",
        "layer": "api_compat_audit_observed_state",
        "entrypoint": "src/api/maas_compat.py",
        "identity_source": "compat_audit_log_request",
    },
    {
        "service_name": "maas-compat-mapek-read",
        "layer": "api_compat_mapek_observed_state",
        "entrypoint": "src/api/maas_compat.py",
        "identity_source": "compat_mapek_event_read_request",
    },
    {
        "service_name": "maas-compat-lifecycle-read",
        "layer": "api_compat_lifecycle_observed_state",
        "entrypoint": "src/api/maas_compat.py",
        "identity_source": "compat_mesh_lifecycle_read_request",
    },
    {
        "service_name": "maas-compat-auth-register",
        "layer": "api_compat_auth_registration_intent",
        "entrypoint": "src/api/maas_compat.py",
        "identity_source": "compat_auth_register_request",
    },
    {
        "service_name": "maas-compat-deploy",
        "layer": "api_compat_lifecycle_control_action",
        "entrypoint": "src/api/maas_compat.py",
        "identity_source": "compat_mesh_deploy_request",
    },
    {
        "service_name": "maas-compat-scale",
        "layer": "api_compat_lifecycle_control_action",
        "entrypoint": "src/api/maas_compat.py",
        "identity_source": "compat_mesh_scale_request",
    },
    {
        "service_name": "maas-compat-terminate",
        "layer": "api_compat_lifecycle_control_action",
        "entrypoint": "src/api/maas_compat.py",
        "identity_source": "compat_mesh_terminate_request",
    },
    {
        "service_name": "maas-compat-billing-pay",
        "layer": "api_compat_billing_pay_intent",
        "entrypoint": "src/api/maas_compat.py",
        "identity_source": "compat_billing_pay_request",
    },
    {
        "service_name": "maas-auth",
        "source_agent": "maas-modular-auth-register",
        "layer": "api_modular_auth_registration_intent",
        "entrypoint": "src/api/maas/endpoints/auth.py",
        "identity_source": "modular_auth_register_request",
    },
    {
        "service_name": "maas-auth",
        "source_agent": "maas-modular-auth-login",
        "layer": "api_modular_auth_login_intent",
        "entrypoint": "src/api/maas/endpoints/auth.py",
        "identity_source": "modular_auth_login_request",
    },
    {
        "service_name": "maas-auth",
        "source_agent": "maas-modular-auth-api-key-rotation",
        "layer": "api_modular_auth_credential_rotation",
        "entrypoint": "src/api/maas/endpoints/auth.py",
        "identity_source": "modular_auth_api_key_rotation_request",
    },
    {
        "service_name": "maas-auth",
        "source_agent": "maas-modular-auth-profile-read",
        "layer": "api_modular_auth_profile_observed_state",
        "entrypoint": "src/api/maas/endpoints/auth.py",
        "identity_source": "modular_auth_profile_request",
    },
    {
        "service_name": "maas-auth",
        "source_agent": "maas-modular-auth-session-control",
        "layer": "api_modular_auth_session_control_action",
        "entrypoint": "src/api/maas/endpoints/auth.py",
        "identity_source": "modular_auth_session_request",
    },
    {
        "service_name": "maas-auth",
        "source_agent": "maas-modular-auth-account-delete",
        "layer": "api_modular_auth_account_delete_control_action",
        "entrypoint": "src/api/maas/endpoints/auth.py",
        "identity_source": "modular_auth_account_delete_request",
    },
    {
        "service_name": "maas-mesh",
        "source_agent": "maas-modular-mesh-deploy",
        "layer": "api_modular_mesh_deploy_control_action",
        "entrypoint": "src/api/maas/endpoints/mesh.py",
        "identity_source": "modular_mesh_deploy_request",
    },
    {
        "service_name": "maas-mesh",
        "source_agent": "maas-modular-mesh-read",
        "layer": "api_modular_mesh_lifecycle_observed_state",
        "entrypoint": "src/api/maas/endpoints/mesh.py",
        "identity_source": "modular_mesh_read_request",
    },
    {
        "service_name": "maas-mesh",
        "source_agent": "maas-modular-mesh-scale",
        "layer": "api_modular_mesh_scale_control_action",
        "entrypoint": "src/api/maas/endpoints/mesh.py",
        "identity_source": "modular_mesh_scale_request",
    },
    {
        "service_name": "maas-mesh",
        "source_agent": "maas-modular-mesh-terminate",
        "layer": "api_modular_mesh_terminate_control_action",
        "entrypoint": "src/api/maas/endpoints/mesh.py",
        "identity_source": "modular_mesh_terminate_request",
    },
    {
        "service_name": "maas-batman",
        "source_agent": "maas-modular-batman-health-read",
        "layer": "api_modular_batman_health_observed_state",
        "entrypoint": "src/api/maas/endpoints/batman.py",
        "identity_source": "modular_batman_health_request",
    },
    {
        "service_name": "maas-batman",
        "source_agent": "maas-modular-batman-metrics-read",
        "layer": "api_modular_batman_metrics_observed_state",
        "entrypoint": "src/api/maas/endpoints/batman.py",
        "identity_source": "modular_batman_metrics_request",
    },
    {
        "service_name": "maas-batman",
        "source_agent": "maas-modular-batman-topology-read",
        "layer": "api_modular_batman_topology_observed_state",
        "entrypoint": "src/api/maas/endpoints/batman.py",
        "identity_source": "modular_batman_topology_request",
    },
    {
        "service_name": "maas-batman",
        "source_agent": "maas-modular-batman-mapek-control",
        "layer": "api_modular_batman_mapek_control_action",
        "entrypoint": "src/api/maas/endpoints/batman.py",
        "identity_source": "modular_batman_mapek_request",
    },
    {
        "service_name": "maas-batman",
        "source_agent": "maas-modular-batman-healing-control",
        "layer": "api_modular_batman_healing_control_action",
        "entrypoint": "src/api/maas/endpoints/batman.py",
        "identity_source": "modular_batman_healing_request",
    },
    {
        "service_name": "maas-pilot",
        "source_agent": "maas-modular-pilot-signup",
        "layer": "api_modular_pilot_signup_control_action",
        "entrypoint": "src/api/maas/endpoints/pilot.py",
        "identity_source": "modular_pilot_signup_request",
    },
    {
        "service_name": "maas-pilot",
        "source_agent": "maas-modular-pilot-status-read",
        "layer": "api_modular_pilot_status_observed_state",
        "entrypoint": "src/api/maas/endpoints/pilot.py",
        "identity_source": "modular_pilot_status_request",
    },
    {
        "service_name": "maas-pilot",
        "source_agent": "maas-modular-pilot-activate",
        "layer": "api_modular_pilot_activation_control_action",
        "entrypoint": "src/api/maas/endpoints/pilot.py",
        "identity_source": "modular_pilot_activate_request",
    },
    {
        "service_name": "maas-billing",
        "source_agent": "maas-modular-billing-payment-intent",
        "layer": "api_modular_billing_payment_intent",
        "entrypoint": "src/api/maas/endpoints/billing.py",
        "identity_source": "modular_billing_payment_request",
    },
    {
        "service_name": "maas-billing",
        "source_agent": "maas-modular-billing-webhook",
        "layer": "api_modular_billing_webhook_lifecycle",
        "entrypoint": "src/api/maas/endpoints/billing.py",
        "identity_source": "modular_billing_webhook_request",
    },
    {
        "service_name": "maas-billing",
        "source_agent": "maas-modular-billing-usage-read",
        "layer": "api_modular_billing_usage_observed_state",
        "entrypoint": "src/api/maas/endpoints/billing.py",
        "identity_source": "modular_billing_usage_request",
    },
    {
        "service_name": "maas-billing",
        "source_agent": "maas-modular-billing-estimate-read",
        "layer": "api_modular_billing_estimate_observed_state",
        "entrypoint": "src/api/maas/endpoints/billing.py",
        "identity_source": "modular_billing_estimate_request",
    },
    {
        "service_name": "maas-billing",
        "source_agent": "maas-modular-billing-plan-read",
        "layer": "api_modular_billing_plan_observed_state",
        "entrypoint": "src/api/maas/endpoints/billing.py",
        "identity_source": "modular_billing_plan_request",
    },
    {
        "service_name": "maas-billing",
        "source_agent": "maas-modular-billing-invoice-generation",
        "layer": "api_modular_billing_invoice_generation",
        "entrypoint": "src/api/maas/endpoints/billing.py",
        "identity_source": "modular_billing_invoice_request",
    },
    {
        "service_name": "maas-nodes",
        "source_agent": "maas-nodes-heartbeat",
        "layer": "api_mesh_to_commerce",
        "entrypoint": "src/api/maas_nodes.py",
        "identity_source": "node_heartbeat_auto_release",
    },
    {
        "service_name": "maas-nodes",
        "source_agent": "maas-modular-node-registration",
        "layer": "api_modular_node_registration_control_action",
        "entrypoint": "src/api/maas/endpoints/nodes.py",
        "identity_source": "modular_node_registration_request",
    },
    {
        "service_name": "maas-nodes",
        "source_agent": "maas-modular-node-heartbeat",
        "layer": "api_modular_node_heartbeat_observed_state",
        "entrypoint": "src/api/maas/endpoints/nodes.py",
        "identity_source": "modular_node_heartbeat_request",
    },
    {
        "service_name": "maas-nodes",
        "source_agent": "maas-modular-node-read",
        "layer": "api_modular_node_observed_state",
        "entrypoint": "src/api/maas/endpoints/nodes.py",
        "identity_source": "modular_node_read_request",
    },
    {
        "service_name": "maas-nodes",
        "source_agent": "maas-modular-node-lifecycle",
        "layer": "api_modular_node_lifecycle_control_action",
        "entrypoint": "src/api/maas/endpoints/nodes.py",
        "identity_source": "modular_node_lifecycle_request",
    },
    {
        "service_name": "maas-telemetry",
        "layer": "api_telemetry_observed_state",
        "entrypoint": "src/api/maas_telemetry.py",
        "identity_source": "telemetry_helper_or_request",
    },
    {
        "service_name": "maas-legacy-heartbeat",
        "layer": "api_legacy_heartbeat_observed_state",
        "entrypoint": "src/api/maas_legacy.py",
        "identity_source": "legacy_heartbeat_request",
    },
    {
        "service_name": "maas-legacy-lifecycle",
        "layer": "api_legacy_lifecycle_control_action",
        "entrypoint": "src/api/maas_legacy.py",
        "identity_source": "legacy_mesh_lifecycle_request",
    },
    {
        "service_name": "maas-legacy-lifecycle-read",
        "layer": "api_legacy_lifecycle_observed_state",
        "entrypoint": "src/api/maas_legacy.py",
        "identity_source": "legacy_mesh_lifecycle_read_request",
    },
    {
        "service_name": "maas-legacy-mapek-read",
        "layer": "api_legacy_mapek_observed_state",
        "entrypoint": "src/api/maas_legacy.py",
        "identity_source": "legacy_mapek_event_read_request",
    },
    {
        "service_name": "maas-legacy-node-lifecycle",
        "layer": "api_legacy_node_lifecycle_control_action",
        "entrypoint": "src/api/maas_legacy.py",
        "identity_source": "legacy_node_lifecycle_request",
    },
    {
        "service_name": "maas-legacy-node-read",
        "layer": "api_legacy_node_observed_state",
        "entrypoint": "src/api/maas_legacy.py",
        "identity_source": "legacy_node_read_request",
    },
    {
        "service_name": "maas-legacy-token-lifecycle",
        "layer": "api_legacy_token_lifecycle_control_action",
        "entrypoint": "src/api/maas_legacy.py",
        "identity_source": "legacy_join_token_rotation_request",
    },
    {
        "service_name": "maas-legacy-policy-lifecycle",
        "layer": "api_legacy_policy_lifecycle_control_action",
        "entrypoint": "src/api/maas_legacy.py",
        "identity_source": "legacy_policy_lifecycle_request",
    },
    {
        "service_name": "maas-legacy-policy-read",
        "layer": "api_legacy_policy_observed_state",
        "entrypoint": "src/api/maas_legacy.py",
        "identity_source": "legacy_policy_read_request",
    },
    {
        "service_name": "maas-billing",
        "layer": "billing_webhook_to_commerce_bridge",
        "entrypoint": "src/api/maas_billing.py",
        "identity_source": "stripe_webhook_metadata",
    },
    {
        "service_name": "maas-billing",
        "source_agent": "maas-billing-invoice",
        "layer": "billing_invoice_generation",
        "entrypoint": "src/api/maas_billing.py",
        "identity_source": "billing_invoice_request",
    },
    {
        "service_name": "maas-billing",
        "source_agent": "maas-billing-checkout",
        "layer": "billing_checkout_intent",
        "entrypoint": "src/api/maas_billing.py",
        "identity_source": "billing_checkout_request",
    },
    {
        "service_name": "maas-billing",
        "source_agent": "maas-billing-customer-portal",
        "layer": "billing_customer_portal_intent",
        "entrypoint": "src/api/maas_billing.py",
        "identity_source": "billing_customer_portal_request",
    },
    {
        "service_name": "maas-billing",
        "source_agent": "maas-billing-history",
        "layer": "billing_history_observed_state",
        "entrypoint": "src/api/maas_billing.py",
        "identity_source": "billing_history_request",
    },
    {
        "service_name": "maas-billing",
        "source_agent": "maas-billing-manual-payment",
        "layer": "billing_manual_payment_mock",
        "entrypoint": "src/api/maas_billing.py",
        "identity_source": "manual_invoice_payment_request",
    },
    {
        "service_name": "maas-billing",
        "source_agent": "maas-billing-subscription-checkout",
        "layer": "billing_subscription_checkout_intent",
        "entrypoint": "src/api/maas_billing.py",
        "identity_source": "billing_subscription_checkout_request",
    },
    {
        "service_name": "maas-billing",
        "source_agent": "maas-billing-subscription-sync",
        "layer": "billing_subscription_sync",
        "entrypoint": "src/api/maas_billing.py",
        "identity_source": "stripe_subscription_sync",
    },
    {
        "service_name": "maas-billing",
        "source_agent": "maas-billing-subscription-webhook",
        "layer": "billing_subscription_webhook_lifecycle",
        "entrypoint": "src/api/maas_billing.py",
        "identity_source": "stripe_subscription_webhook",
    },
    {
        "service_name": "maas-billing",
        "source_agent": "maas-legacy-billing",
        "layer": "billing_webhook_to_commerce_bridge",
        "entrypoint": "src/api/maas_legacy.py",
        "identity_source": "legacy_billing_webhook_request",
    },
    {
        "service_name": "maas-billing",
        "source_agent": "maas-legacy-billing-usage",
        "layer": "billing_usage_observed_state",
        "entrypoint": "src/api/maas_legacy.py",
        "identity_source": "legacy_billing_usage_request",
    },
    {
        "service_name": "billing-api-config-read",
        "layer": "api_billing_config_observed_state",
        "entrypoint": "src/api/billing.py",
        "identity_source": "billing_config_request",
    },
    {
        "service_name": "billing-api-checkout-session",
        "layer": "api_billing_checkout_intent",
        "entrypoint": "src/api/billing.py",
        "identity_source": "billing_checkout_session_request",
    },
    {
        "service_name": "billing-api-stripe-webhook",
        "layer": "api_billing_webhook_lifecycle",
        "entrypoint": "src/api/billing.py",
        "identity_source": "billing_stripe_webhook_request",
    },
    {
        "service_name": "billing-api-order-status-read",
        "layer": "api_billing_order_status_observed_state",
        "entrypoint": "src/api/billing.py",
        "identity_source": "billing_order_status_request",
    },
    {
        "service_name": "billing-api-revenue-metrics-read",
        "layer": "api_billing_revenue_observed_state",
        "entrypoint": "src/api/billing.py",
        "identity_source": "billing_revenue_metrics_request",
    },
    {
        "service_name": "maas-agent-health-status-read",
        "layer": "api_agent_mesh_health_observed_state",
        "entrypoint": "src/api/maas_agent_mesh.py",
        "identity_source": "agent_health_status_request_user",
    },
    {
        "service_name": "maas-agent-health-run",
        "layer": "api_agent_mesh_health_control_action",
        "entrypoint": "src/api/maas_agent_mesh.py",
        "identity_source": "agent_health_run_request_user",
    },
    {
        "service_name": "maas-agent-health-history-read",
        "layer": "api_agent_mesh_health_observed_state",
        "entrypoint": "src/api/maas_agent_mesh.py",
        "identity_source": "agent_health_history_request_user",
    },
    {
        "service_name": "maas-provisioning-setup-generate",
        "layer": "api_provisioning_node_join_control_action",
        "entrypoint": "src/api/maas_provisioning.py",
        "identity_source": "provisioning_generate_setup_request_user",
    },
)


def service_identity_registry_status() -> Dict[str, object]:
    """Return redacted identity configuration status for all known services."""
    services: List[Dict[str, object]] = []
    for registration in KNOWN_EVENT_IDENTITY_SERVICES:
        status = service_event_identity_status(
            service_name=registration["service_name"]
        )
        services.append({**registration, **status})

    return {
        "status": "ok",
        "claim_boundary": IDENTITY_STATUS_CLAIM_BOUNDARY,
        "redacted": True,
        "identity_fields": [
            "spiffe_id",
            "did",
            "wallet_address",
        ],
        "services_total": len(services),
        "services_with_any_identity": sum(
            1 for service in services if service["configured_fields"]
        ),
        "services_complete": sum(1 for service in services if service["complete"]),
        "services": services,
    }
