// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadMeshcore returns the embedded CollectionSpec for meshcore.
func loadMeshcore() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MeshcoreBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load meshcore: %w", err)
	}

	return spec, err
}

// loadMeshcoreObjects loads meshcore and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*meshcoreObjects
//	*meshcorePrograms
//	*meshcoreMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadMeshcoreObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadMeshcore()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// meshcoreSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type meshcoreSpecs struct {
	meshcoreProgramSpecs
	meshcoreMapSpecs
	meshcoreVariableSpecs
}

// meshcoreProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type meshcoreProgramSpecs struct {
	XdpMeshFilterProg *ebpf.ProgramSpec `ebpf:"xdp_mesh_filter_prog"`
}

// meshcoreMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type meshcoreMapSpecs struct {
	MeshRoutes  *ebpf.MapSpec `ebpf:"mesh_routes"`
	ObfConfig   *ebpf.MapSpec `ebpf:"obf_config"`
	PacketStats *ebpf.MapSpec `ebpf:"packet_stats"`
}

// meshcoreVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type meshcoreVariableSpecs struct {
}

// meshcoreObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadMeshcoreObjects or ebpf.CollectionSpec.LoadAndAssign.
type meshcoreObjects struct {
	meshcorePrograms
	meshcoreMaps
	meshcoreVariables
}

func (o *meshcoreObjects) Close() error {
	return _MeshcoreClose(
		&o.meshcorePrograms,
		&o.meshcoreMaps,
	)
}

// meshcoreMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadMeshcoreObjects or ebpf.CollectionSpec.LoadAndAssign.
type meshcoreMaps struct {
	MeshRoutes  *ebpf.Map `ebpf:"mesh_routes"`
	ObfConfig   *ebpf.Map `ebpf:"obf_config"`
	PacketStats *ebpf.Map `ebpf:"packet_stats"`
}

func (m *meshcoreMaps) Close() error {
	return _MeshcoreClose(
		m.MeshRoutes,
		m.ObfConfig,
		m.PacketStats,
	)
}

// meshcoreVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadMeshcoreObjects or ebpf.CollectionSpec.LoadAndAssign.
type meshcoreVariables struct {
}

// meshcorePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadMeshcoreObjects or ebpf.CollectionSpec.LoadAndAssign.
type meshcorePrograms struct {
	XdpMeshFilterProg *ebpf.Program `ebpf:"xdp_mesh_filter_prog"`
}

func (p *meshcorePrograms) Close() error {
	return _MeshcoreClose(
		p.XdpMeshFilterProg,
	)
}

func _MeshcoreClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed meshcore_arm64_bpfel.o
var _MeshcoreBytes []byte
