from __future__ import annotations
import argparse
import json
import sys
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

class BriefGenerator:
    """
    Generates beautiful Markdown briefs from filtered news.
    """

    def __init__(self, project_name: str = "x0tta6bl4"):
        self.project_name = project_name

    def generate_markdown(self, filtered_news: List[Dict[str, Any]], actions: List[str]) -> str:
        """
        Creates a formatted Markdown brief.
        """
        date_str = datetime.now().strftime("%Y-%m-%d")
        
        lines = [
            f"# 🧭 {self.project_name} Visionary Brief: {date_str}",
            "\n> 'The future is already here – it's just not evenly distributed.'\n",
            "## 📡 Filtered Intelligence",
            "| Category | News Title | Relevance | Actionable Insight |",
            "| :--- | :--- | :--- | :--- |"
        ]
        
        for i, item in enumerate(filtered_news[:5]):
            relevance_stars = "⭐" * int(item["relevance_score"] * 5) or "▫️"
            action = actions[i] if i < len(actions) else "Monitor for further developments."
            
            lines.append(
                f"| **{item['category']}** | [{item['title']}]({item['url']}) | {relevance_stars} | {action} |"
            )
            
        lines.append("\n## 🛠️ Key Action Items for this week")
        for step in actions:
            lines.append(f"- [ ] {step}")
            
        lines.append("\n---\n*Generated by x0tta6bl4 AI Navigator Agent*")
        
        return "\n".join(lines)


def _read_json(path: str) -> Any:
    if path == "-":
        return json.loads(sys.stdin.read())
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def _coerce_news(payload: Any) -> List[Dict[str, Any]]:
    if isinstance(payload, dict):
        payload = payload.get("filtered_news", payload.get("news"))
    if not isinstance(payload, list) or not all(
        isinstance(item, dict) for item in payload
    ):
        raise ValueError("news input must be a JSON list or an object with filtered_news")
    return payload


def _coerce_actions(payload: Any) -> List[str]:
    if isinstance(payload, dict):
        payload = payload.get("actions")
    if payload is None:
        return []
    if not isinstance(payload, list) or not all(
        isinstance(item, str) for item in payload
    ):
        raise ValueError("actions input must be a JSON string list")
    return payload


def load_brief_inputs(
    news_path: str,
    actions_path: Optional[str] = None,
) -> Tuple[List[Dict[str, Any]], List[str]]:
    """Load brief inputs from JSON files or stdin via '-'."""
    news_payload = _read_json(news_path)
    actions_payload = _read_json(actions_path) if actions_path else news_payload
    return _coerce_news(news_payload), _coerce_actions(actions_payload)


def _build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate an AI navigation brief.")
    parser.add_argument(
        "--news",
        required=True,
        help="Path to JSON list, JSON object with filtered_news, or '-' for stdin.",
    )
    parser.add_argument(
        "--actions",
        help="Optional path to JSON string list or JSON object with actions.",
    )
    parser.add_argument("--project-name", default="x0tta6bl4")
    return parser


def main(argv: Optional[List[str]] = None) -> int:
    parser = _build_arg_parser()
    args = parser.parse_args(argv)
    try:
        news, actions = load_brief_inputs(args.news, args.actions)
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        parser.error(str(exc))

    print(BriefGenerator(args.project_name).generate_markdown(news, actions))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

