
"""add_escrow_auto_renew_fields

Revision ID: b49070d1c83b
Revises: 30552aa07b45
Create Date: 2026-03-01 10:35:00

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b49070d1c83b'
down_revision: Union[str, None] = '30552aa07b45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_escrows', sa.Column('auto_renew', sa.Boolean(), nullable=True))
    op.add_column('marketplace_escrows', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketplace_escrows', 'expires_at')
    op.drop_column('marketplace_escrows', 'auto_renew')
    # ### end Alembic commands ###
