// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64be || armbe || mips || mips64 || mips64p32 || ppc64 || s390 || s390x || sparc || sparc64

package sensor

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadNetworkSensor returns the embedded CollectionSpec for NetworkSensor.
func LoadNetworkSensor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetworkSensorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load NetworkSensor: %w", err)
	}

	return spec, err
}

// LoadNetworkSensorObjects loads NetworkSensor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NetworkSensorObjects
//	*NetworkSensorPrograms
//	*NetworkSensorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNetworkSensorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNetworkSensor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NetworkSensorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkSensorSpecs struct {
	NetworkSensorProgramSpecs
	NetworkSensorMapSpecs
}

// NetworkSensorSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkSensorProgramSpecs struct {
	XdpRstSensor *ebpf.ProgramSpec `ebpf:"xdp_rst_sensor"`
}

// NetworkSensorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkSensorMapSpecs struct {
	RstCount *ebpf.MapSpec `ebpf:"rst_count"`
}

// NetworkSensorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkSensorObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkSensorObjects struct {
	NetworkSensorPrograms
	NetworkSensorMaps
}

func (o *NetworkSensorObjects) Close() error {
	return _NetworkSensorClose(
		&o.NetworkSensorPrograms,
		&o.NetworkSensorMaps,
	)
}

// NetworkSensorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkSensorObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkSensorMaps struct {
	RstCount *ebpf.Map `ebpf:"rst_count"`
}

func (m *NetworkSensorMaps) Close() error {
	return _NetworkSensorClose(
		m.RstCount,
	)
}

// NetworkSensorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkSensorObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkSensorPrograms struct {
	XdpRstSensor *ebpf.Program `ebpf:"xdp_rst_sensor"`
}

func (p *NetworkSensorPrograms) Close() error {
	return _NetworkSensorClose(
		p.XdpRstSensor,
	)
}

func _NetworkSensorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed networksensor_bpfeb.o
var _NetworkSensorBytes []byte
