#!/bin/bash
# Helper script for finding prospects
# This script provides search queries and templates

echo "🔍 x0tta6bl4 Prospects Finder"
echo "=============================="
echo ""

echo "📋 LINKEDIN SEARCH QUERIES:"
echo ""
echo "1. Enterprise CTOs:"
echo "   'CTO' OR 'VP Engineering' AND 'infrastructure' AND '500-10,000 employees'"
echo ""
echo "2. Security Directors:"
echo "   'Security Director' OR 'CISO' AND 'compliance' AND 'government'"
echo ""
echo "3. DevOps Leads:"
echo "   'DevOps Lead' AND 'Kubernetes' AND 'enterprise'"
echo ""
echo "4. Government/Defense:"
echo "   'CTO' AND 'government' AND 'security'"
echo ""

echo "🌐 OTHER PLACES TO SEARCH:"
echo ""
echo "1. HackerNews:"
echo "   - https://news.ycombinator.com/jobs"
echo "   - Search for 'infrastructure', 'security', 'quantum'"
echo ""
echo "2. Reddit:"
echo "   - r/devops"
echo "   - r/kubernetes"
echo "   - r/cybersecurity"
echo ""
echo "3. GitHub:"
echo "   - Search for Kubernetes projects"
echo "   - Look for security-focused projects"
echo ""

echo "📝 RESEARCH CHECKLIST:"
echo ""
echo "For each prospect, research:"
echo "  [ ] Company size and industry"
echo "  [ ] Current technology stack"
echo "  [ ] Recent news/challenges"
echo "  [ ] Pain points x0tta6bl4 solves"
echo "  [ ] Email address"
echo "  [ ] LinkedIn profile"
echo ""

echo "✅ NEXT STEPS:"
echo ""
echo "1. Open LinkedIn and start searching"
echo "2. For each prospect, fill PROSPECTS_LIST.md"
echo "3. Research company (5 min per prospect)"
echo "4. Prepare personalized email"
echo ""

echo "📊 TARGET: 10 prospects by end of day"
echo ""

