#!/bin/bash
# CHANGELOG.md generator from git history
# Usage: bash generate_changelog.sh [repo_path] [output_file]

set -euo pipefail

REPO_PATH="${1:-.}"
OUTPUT_FILE="${2:-CHANGELOG.md}"

cd "$REPO_PATH"

# Get last tag
LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

if [ -z "$LAST_TAG" ]; then
    echo "No tags found. Using all commits."
    COMMITS=$(git log --pretty=format:"%H|%s|%an" --no-merges)
else
    echo "Using commits since $LAST_TAG"
    COMMITS=$(git log "${LAST_TAG}..HEAD" --pretty=format:"%H|%s|%an" --no-merges)
fi

# Initialize arrays
ADDED=()
FIXED=()
CHANGED=()
REMOVED=()

# Categorize commits
while IFS='|' read -r hash subject author; do
    [ -z "$hash" ] && continue
    
    # Categorize based on conventional commits or keywords
    subject_lower=$(echo "$subject" | tr '[:upper:]' '[:lower:]')
    
    if echo "$subject_lower" | grep -qE "^feat|^add|^new|^[+].*"; then
        ADDED+=("- $subject ($hash)")
    elif echo "$subject_lower" | grep -qE "^fix|^bugfix|^patch|^[!].*"; then
        FIXED+=("- $subject ($hash)")
    elif echo "$subject_lower" | grep -qE "^refactor|^perf|^style|^ci|^docs|^chore|^[~].*"; then
        CHANGED+=("- $subject ($hash)")
    elif echo "$subject_lower" | grep -qE "^remove|^delete|^deprecate|^[-].*"; then
        REMOVED+=("- $subject ($hash)")
    else
        CHANGED+=("- $subject ($hash)")
    fi
done <<< "$COMMITS"

# Generate CHANGELOG
{
    echo "# Changelog"
    echo ""
    if [ -n "$LAST_TAG" ]; then
        echo "## Changes since $LAST_TAG"
    else
        echo "## All changes"
    fi
    echo ""
    echo "Generated on $(date -u +%Y-%m-%d)"
    echo ""
    
    if [ ${#ADDED[@]} -gt 0 ]; then
        echo "### Added"
        echo ""
        printf '%s\n' "${ADDED[@]}"
        echo ""
    fi
    
    if [ ${#FIXED[@]} -gt 0 ]; then
        echo "### Fixed"
        echo ""
        printf '%s\n' "${FIXED[@]}"
        echo ""
    fi
    
    if [ ${#CHANGED[@]} -gt 0 ]; then
        echo "### Changed"
        echo ""
        printf '%s\n' "${CHANGED[@]}"
        echo ""
    fi
    
    if [ ${#REMOVED[@]} -gt 0 ]; then
        echo "### Removed"
        echo ""
        printf '%s\n' "${REMOVED[@]}"
        echo ""
    fi
    
    echo "---"
    echo "*Generated by generate_changelog.sh*"
} > "$OUTPUT_FILE"

echo "CHANGELOG generated: $OUTPUT_FILE"
echo "Stats: Added=${#ADDED[@]}, Fixed=${#FIXED[@]}, Changed=${#CHANGED[@]}, Removed=${#REMOVED[@]}"
