version: '3.8'

services:
  x0tta6bl4-app:
    image: x0tta6bl4-app:staging
    container_name: x0tta6bl4-production
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - NODE_ID=production-control-plane
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./data:/app/data
    networks:
      - x0tta6bl4-network

networks:
  x0tta6bl4-network:
    driver: bridge

