agent {
    trust_domain = "x0tta6bl4.mesh"
    server_address = "127.0.0.1"
    server_port = "8081"
    socket_path = "/opt/spire/sockets/agent.sock"
    data_dir = "/opt/spire/data/agent"
    log_level = "WARN"
    log_file = "/opt/spire/logs/agent.log"

    insecure_bootstrap = false
    trust_bundle_path = "/opt/spire/conf/agent/bootstrap.crt"

    workload_x509_svid_key_type = "EC_P256"
    workload_x509_svid_ttl = "3600"
}

plugins {
    NodeAttestor "join_token" {
        plugin_data {}
    }

    WorkloadAttestor "unix" {
        plugin_data {
            discover_workload_path = true
        }
    }
}
