apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gateway.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.nodeEnv | quote }}
  LOG_LEVEL: {{ .Values.logLevel | quote }}
  MESH_API_URL: {{ .Values.meshApiUrl | quote }}
  PORT: {{ .Values.service.port | quote }}
