from typing import List, Dict, Any
from datetime import datetime

class BriefGenerator:
    """
    Generates beautiful Markdown briefs from filtered news.
    """

    def __init__(self, project_name: str = "x0tta6bl4"):
        self.project_name = project_name

    def generate_markdown(self, filtered_news: List[Dict[str, Any]], actions: List[str]) -> str:
        """
        Creates a formatted Markdown brief.
        """
        date_str = datetime.now().strftime("%Y-%m-%d")
        
        lines = [
            f"# 🧭 {self.project_name} Visionary Brief: {date_str}",
            "\n> 'The future is already here – it's just not evenly distributed.'\n",
            "## 📡 Filtered Intelligence",
            "| Category | News Title | Relevance | Actionable Insight |",
            "| :--- | :--- | :--- | :--- |"
        ]
        
        for i, item in enumerate(filtered_news[:5]):
            relevance_stars = "⭐" * int(item["relevance_score"] * 5) or "▫️"
            action = actions[i] if i < len(actions) else "Monitor for further developments."
            
            lines.append(
                f"| **{item['category']}** | [{item['title']}]({item['url']}) | {relevance_stars} | {action} |"
            )
            
        lines.append("\n## 🛠️ Key Action Items for this week")
        for step in actions:
            lines.append(f"- [ ] {step}")
            
        lines.append("\n---\n*Generated by x0tta6bl4 AI Navigator Agent*")
        
        return "\n".join(lines)

if __name__ == "__main__":
    # Mock data for demonstration
    mock_news = [
        {"category": "BENCHMARK", "title": "NIST Finalizes PQC Standards", "url": "https://nist.gov", "relevance_score": 0.8},
        {"category": "BUSINESS", "title": "Competitor X launches eBPF-based mesh", "url": "#", "relevance_score": 0.6}
    ]
    mock_actions = [
        "COMPLIANCE: Verify our implementation matches FIPS 203 final spec.",
        "BENCHMARK: Compare XDP performance with Competitor X's latest release."
    ]
    
    generator = BriefGenerator()
    print(generator.generate_markdown(mock_news, mock_actions))
