agent {
    trust_domain = "x0tta6bl4.mesh"
    log_level = "INFO"
    data_dir = "/var/lib/spire/agent"
    server_address = "spire-server"
    server_port = "8081"
    join_token = "e4f2f5ad-7bfa-4f7e-9944-ad9245d79b9a"
    insecure_bootstrap = true
}

plugins {
    NodeAttestor "join_token" {
        plugin_data {}
    }
    KeyManager "memory" {
        plugin_data {}
    }
    WorkloadAttestor "unix" {
        plugin_data {
            discover_workload_path = true
        }
    }
}
