agent {
    trust_domain = "x0tta6bl4.mesh"
    log_level = "INFO"
    data_dir = "/var/lib/spire/agent"
    server_address = "spire-server"
    server_port = "8081"
    join_token = "71fd2662-3cb9-4c3e-8a81-503074287441"
    insecure_bootstrap = true
}

plugins {
    NodeAttestor "join_token" {
        plugin_data {}
    }
    KeyManager "memory" {
        plugin_data {}
    }
    WorkloadAttestor "unix" {
        plugin_data {
            discover_workload_path = true
        }
    }
}
