agent {
    trust_domain = "x0tta6bl4.mesh"
    log_level = "INFO"
    data_dir = "/var/lib/spire/agent"
    server_address = "89.125.1.107"
    server_port = "8081"
    join_token = "0eee46fa-74e9-449e-a6c1-0a7d5094762c"
    insecure_bootstrap = true
}

plugins {
    KeyManager "memory" {
        plugin_data {}
    }
    NodeAttestor "join_token" {
        plugin_data {}
    }
    WorkloadAttestor "unix" {
        plugin_data {}
    }
}
