// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadBandwidthMonitor returns the embedded CollectionSpec for BandwidthMonitor.
func LoadBandwidthMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BandwidthMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load BandwidthMonitor: %w", err)
	}

	return spec, err
}

// LoadBandwidthMonitorObjects loads BandwidthMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BandwidthMonitorObjects
//	*BandwidthMonitorPrograms
//	*BandwidthMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBandwidthMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBandwidthMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BandwidthMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BandwidthMonitorSpecs struct {
	BandwidthMonitorProgramSpecs
	BandwidthMonitorMapSpecs
}

// BandwidthMonitorSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BandwidthMonitorProgramSpecs struct {
	MonitorBandwidth *ebpf.ProgramSpec `ebpf:"monitor_bandwidth"`
}

// BandwidthMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BandwidthMonitorMapSpecs struct {
	BandwidthMap *ebpf.MapSpec `ebpf:"bandwidth_map"`
}

// BandwidthMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBandwidthMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type BandwidthMonitorObjects struct {
	BandwidthMonitorPrograms
	BandwidthMonitorMaps
}

func (o *BandwidthMonitorObjects) Close() error {
	return _BandwidthMonitorClose(
		&o.BandwidthMonitorPrograms,
		&o.BandwidthMonitorMaps,
	)
}

// BandwidthMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBandwidthMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type BandwidthMonitorMaps struct {
	BandwidthMap *ebpf.Map `ebpf:"bandwidth_map"`
}

func (m *BandwidthMonitorMaps) Close() error {
	return _BandwidthMonitorClose(
		m.BandwidthMap,
	)
}

// BandwidthMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBandwidthMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type BandwidthMonitorPrograms struct {
	MonitorBandwidth *ebpf.Program `ebpf:"monitor_bandwidth"`
}

func (p *BandwidthMonitorPrograms) Close() error {
	return _BandwidthMonitorClose(
		p.MonitorBandwidth,
	)
}

func _BandwidthMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bandwidthmonitor_bpfel_x86.o
var _BandwidthMonitorBytes []byte
