// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadConnectionTracker returns the embedded CollectionSpec for ConnectionTracker.
func LoadConnectionTracker() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ConnectionTrackerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ConnectionTracker: %w", err)
	}

	return spec, err
}

// LoadConnectionTrackerObjects loads ConnectionTracker and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ConnectionTrackerObjects
//	*ConnectionTrackerPrograms
//	*ConnectionTrackerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadConnectionTrackerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadConnectionTracker()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ConnectionTrackerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ConnectionTrackerSpecs struct {
	ConnectionTrackerProgramSpecs
	ConnectionTrackerMapSpecs
}

// ConnectionTrackerSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ConnectionTrackerProgramSpecs struct {
	TcpV4Connect *ebpf.ProgramSpec `ebpf:"tcp_v4_connect"`
}

// ConnectionTrackerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ConnectionTrackerMapSpecs struct {
	ConnMap   *ebpf.MapSpec `ebpf:"conn_map"`
	ConnTotal *ebpf.MapSpec `ebpf:"conn_total"`
}

// ConnectionTrackerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadConnectionTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type ConnectionTrackerObjects struct {
	ConnectionTrackerPrograms
	ConnectionTrackerMaps
}

func (o *ConnectionTrackerObjects) Close() error {
	return _ConnectionTrackerClose(
		&o.ConnectionTrackerPrograms,
		&o.ConnectionTrackerMaps,
	)
}

// ConnectionTrackerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadConnectionTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type ConnectionTrackerMaps struct {
	ConnMap   *ebpf.Map `ebpf:"conn_map"`
	ConnTotal *ebpf.Map `ebpf:"conn_total"`
}

func (m *ConnectionTrackerMaps) Close() error {
	return _ConnectionTrackerClose(
		m.ConnMap,
		m.ConnTotal,
	)
}

// ConnectionTrackerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadConnectionTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type ConnectionTrackerPrograms struct {
	TcpV4Connect *ebpf.Program `ebpf:"tcp_v4_connect"`
}

func (p *ConnectionTrackerPrograms) Close() error {
	return _ConnectionTrackerClose(
		p.TcpV4Connect,
	)
}

func _ConnectionTrackerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed connectiontracker_bpfel_x86.o
var _ConnectionTrackerBytes []byte
