// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type LatencyTrackerLatencyValue struct {
	LastTimestampNs uint64
	PktCount        uint64
}

// LoadLatencyTracker returns the embedded CollectionSpec for LatencyTracker.
func LoadLatencyTracker() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LatencyTrackerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load LatencyTracker: %w", err)
	}

	return spec, err
}

// LoadLatencyTrackerObjects loads LatencyTracker and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*LatencyTrackerObjects
//	*LatencyTrackerPrograms
//	*LatencyTrackerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadLatencyTrackerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadLatencyTracker()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// LatencyTrackerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type LatencyTrackerSpecs struct {
	LatencyTrackerProgramSpecs
	LatencyTrackerMapSpecs
}

// LatencyTrackerSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type LatencyTrackerProgramSpecs struct {
	TrackLatency *ebpf.ProgramSpec `ebpf:"track_latency"`
}

// LatencyTrackerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type LatencyTrackerMapSpecs struct {
	LatencyMap *ebpf.MapSpec `ebpf:"latency_map"`
}

// LatencyTrackerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadLatencyTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type LatencyTrackerObjects struct {
	LatencyTrackerPrograms
	LatencyTrackerMaps
}

func (o *LatencyTrackerObjects) Close() error {
	return _LatencyTrackerClose(
		&o.LatencyTrackerPrograms,
		&o.LatencyTrackerMaps,
	)
}

// LatencyTrackerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadLatencyTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type LatencyTrackerMaps struct {
	LatencyMap *ebpf.Map `ebpf:"latency_map"`
}

func (m *LatencyTrackerMaps) Close() error {
	return _LatencyTrackerClose(
		m.LatencyMap,
	)
}

// LatencyTrackerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadLatencyTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type LatencyTrackerPrograms struct {
	TrackLatency *ebpf.Program `ebpf:"track_latency"`
}

func (p *LatencyTrackerPrograms) Close() error {
	return _LatencyTrackerClose(
		p.TrackLatency,
	)
}

func _LatencyTrackerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed latencytracker_bpfel_arm64.o
var _LatencyTrackerBytes []byte
